In [1]:
import pandas as pd

In [2]:
import numpy as np
import sklearn

In [3]:
f="C:/Users/Asus/Downloads/ch-olatest/test.csv"

In [5]:
f1="C:/Users/Asus/Downloads/ch-olatrain/train.csv"

In [6]:
train=pd.read_csv(f1)

C:\Users\Asus\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (1,4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
test=pd.read_csv(f)

In [8]:
train

,ID,vendor+AF8-id,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,pickup+AF8-time,drop+AF8-time,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,stored+AF8-flag,extra+AF8-charges,improvement+AF8-charge,total+AF8-amount
0,0,1,170.0,233.0,1.83,0.5,0.70,04/04/2017 05:59:43 PM,04/04/2017 06:05:04 PM,1.0,0,1.0,1.0,N,1,0.3,9.13
1,1,2,151.0,243.0,3.56,0.5,4.64,04/03/2017 07:03:34 PM,04/03/2017 07:20:04 PM,1.0,0,1.0,1.0,N,1,0.3,21.36
2,2,2,68.0,90.0,1.5,0.5,1.29,04/03/2017 03:06:13 PM,04/03/2017 03:12:30 PM,2.0,0,1.0,1.0,N,0,0.3,8.8
3,3,2,142.0,234.0,1.5,0.5,2.74,04/04/2017 08:10:52 AM,04/04/2017 08:27:00 AM,1.0,0,1.0,1.0,N,0,0.3,14.8
4,4,2,238.0,238.0,0,0.5,0.45,04/05/2017 02:02:59 PM,04/05/2017 02:05:41 PM,6.0,0,2.0,1.0,N,0,0.3,4.8
5,5,1,230.0,48.0,1.05,0.5,0.40,04/03/2017 09:10:13 AM,04/03/2017 09:12:09 AM,1.0,0,1.0,1.0,N,0,0.3,5.35
6,6,2,236.0,140.0,2.46,0.5,1.72,04/03/2017 12:04:52 PM,04/03/2017 12:20:54 PM,3.0,0,1.0,1.0,N,0,0.3,14.76
7,7,1,236.0,13.0,5.95,0.5,8.80,04/04/2017 03:19:38 PM,04/04/2017 03:48:18 PM,1.0,0,1.0,1.0,N,0,0.3,35.75
8,8,1,229.0,141.0,0,0.5,1.20,04/05/2017 09:16:22 PM,04/05/2017 09:24:26 PM,2.0,0,2.0,1.0,N,0.5,0.3,8.8
9,9,1,132.0,164.0,0,0.5,17.00,04/06/2017 07:38:53 PM,04/06/2017 08:17:01 PM,2.0,5.76,2.0,2.0,N,4.5,0.3,63.06
10,10,2,114.0,170.0,2.58,0.5,1.54,04/06/2017 06:05:00 PM,04/06/2017 06:15:30 PM,1.0,0,1.0,1.0,N,1,0.3,12.88
11,11,1,264.0,264.0,1.25,0.5,0.70,04/06/2017 08:13:58 PM,04/06/2017 08:18:25 PM,1.0,0,1.0,1.0,N,0.5,0.3,7.55
12,12,2,238.0,151.0,1.3,0.5,0.59,04/03/2017 04:04:51 PM,04/03/2017 04:10:30 PM,1.0,0,1.0,1.0,N,1,0.3,8.6
13,13,1,170.0,246.0,2.65,0.5,1.90,04/04/2017 08:13:50 AM,04/04/2017 08:30:44 AM,1.0,0,1.0,1.0,N,0,0.3,15.95
14,14,1,166.0,238.0,1.55,0.5,1.30,04/03/2017 05:14:57 PM,04/03/2017 05:19:39 PM,1.0,0,1.0,1.0,N,1,0.3,9.35
15,15,2,263.0,138.0,0,0.5,6.95,04/07/2017 09:32:20 AM,04/07/2017 09:51:05 AM,1.0,5.76,1.0,1.0,N,0,0.3,29.06
16,16,2,137.0,79.0,0,0.5,1.17,04/06/2017 09:42:34 PM,04/06/2017 09:48:39 PM,1.0,0,2.0,1.0,N,0.5,0.3,7.8
17,17,1,90.0,230.0,0,0.5,1.60,04/05/2017 08:26:54 AM,04/05/2017 08:39:18 AM,1.0,0,2.0,1.0,N,0,0.3,10.3
18,18,2,141.0,263.0,1,0.5,1.00,04/05/2017 04:06:52 PM,04/05/2017 04:11:23 PM,1.0,0,1.0,1.0,N,1,0.3,8.3
19,19,1,264.0,264.0,0,0.5,2.20,04/03/2017 08:52:11 AM,04/03/2017 09:05:20 AM,1.0,0,2.0,1.0,N,0,0.3,11.8
20,20,2,211.0,90.0,1,0.5,1.73,04/03/2017 05:30:54 PM,04/03/2017 05:41:11 PM,1.0,0,1.0,1.0,N,1,0.3,11.3
21,21,2,138.0,232.0,4,0.5,8.92,04/06/2017 01:41:14 PM,04/06/2017 02:08:36 PM,3.0,5.54,1.0,1.0,N,0,0.3,38.84
22,22,1,164.0,170.0,0.95,0.5,0.40,04/06/2017 06:57:09 AM,04/06/2017 07:00:01 AM,1.0,0,1.0,1.0,N,0,0.3,5.75
23,23,1,141.0,170.0,3,0.5,2.30,04/07/2017 01:46:13 PM,04/07/2017 02:00:29 PM,1.0,0,1.0,1.0,N,0,0.3,15.3
24,24,1,68.0,143.0,1.03,0.5,1.90,04/04/2017 04:34:12 PM,04/04/2017 04:43:26 PM,1.0,0,1.0,1.0,N,1,0.3,11.33
25,25,2,148.0,79.0,1.96,0.5,1.17,04/05/2017 07:04:52 PM,04/05/2017 07:14:41 PM,2.0,0,1.0,1.0,N,1,0.3,11.76
26,26,1,138.0,229.0,4,0.5,9.90,04/07/2017 02:50:34 PM,04/07/2017 03:18:40 PM,1.0,5.76,1.0,1.0,N,0,0.3,40.06
27,27,2,237.0,170.0,2.82,0.5,0.89,04/06/2017 09:35:09 AM,04/06/2017 09:51:52 AM,2.0,0,1.0,1.0,N,0,0.3,14.12
28,28,2,261.0,164.0,0,0.5,4.60,04/06/2017 04:16:23 PM,04/06/2017 05:01:32 PM,4.0,0,2.0,1.0,N,1,0.3,29.3
29,29,1,236.0,50.0,0.22,0.5,2.60,04/04/2017 02:29:36 PM,04/04/2017 02:48:46 PM,1.0,0,1.0,1.0,N,0,0.3,15.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048545,1048545,2,186.0,236.0,3.96,0.5,3.85,04/05/2017 12:07:44 PM,04/05/2017 12:33:45 PM,1.0,0,1.0,1.0,N,0,0.3,23.76
1048546,1048546,2,238.0,113.0,3.5,0.5,6.45,04/03/2017 09:03:45 AM,04/03/2017 09:41:12 AM,2.0,0,1.0,1.0,N,0,0.3,30.3
1048547,1048547,1,143.0,50.0,2.2,0.5,0.90,04/05/2017 07:43:05 AM,04/05/2017 07:53:40 AM,1.0,0,1.0,1.0,N,0,0.3,11
1048548,1048548,1,263.0,263.0,0.79,0.5,0.40,04/06/2017 06:00:14 PM,04/06/2017 06:02:24 PM,1.0,0,1.0,1.0,N,1,0.3,6.09
1048549,1048549,1,113.0,79.0,1.15,0.5,0.50,04/03/2017 09:06:41 PM,04/03/2017 09:11:08 PM,1.0,0,1.0,1.0,N,0.5,0.3,6.95
1048550,1048550,2,237.0,237.0,1.89,0.5,0.69,04/06/2017 10:35:44 AM,04/06/2017 10:41:17 AM,1.0,0,1.0,1.0,N,0,0.3,8.19
1048551,1048551,1,234.0,186.0,0,0.5,0.90,04/06/2017 02:06:36 AM,04/06/2017 02:11:15 AM,1.0,0,2.0,1.0,N,0.5,0.3,6.3
1048552,1048552,2,142.0,141.0,0,0.5,1.37,04/06/2017 02:19:09 PM,04/06/2017 02:35:05 PM,1.0,0,2.0,1.0,N,0,0.3,11.8
1048553,1048553,2,113.0,79.0,1.56,0.5,0.93,04/05/2017 08:47:38 PM,04/05/2017 08:55:23 PM,2.0,0,1.0,1.0,N,0.5,0.3,9.36
1048554,1048554,2,48.0,161.0,0,0.5,1.04,04/05/2017 10:52:42 AM,04/05/2017 11:02:03 AM,3.0,0,2.0,1.0,N,0,0.3,8.3
1048555,1048555,1,107.0,230.0,2.35,0.5,2.40,04/03/2017 10:18:47 PM,04/03/2017 10:30:24 PM,1.0,0,1.0,1.0,N,0.5,0.3,14.15
1048556,1048556,1,164.0,161.0,0,0.5,1.00,04/05/2017 03:38:10 PM,04/05/2017 03:43:24 PM,1.0,0,2.0,1.0,N,0,0.3,6.3
1048557,1048557,2,237.0,237.0,1.16,0.5,0.67,04/03/2017 12:17:50 PM,04/03/2017 12:22:38 PM,1.0,0,1.0,1.0,N,0,0.3,6.96
1048558,1048558,2,239.0,142.0,1.36,0.5,0.59,04/03/2017 06:38:05 PM,04/03/2017 06:42:42 PM,1.0,0,1.0,1.0,N,1,0.3,8.16
1048559,1048559,2,90.0,125.0,1,0.5,1.31,04/06/2017 09:28:46 AM,04/06/2017 09:36:24 AM,1.0,0,1.0,1.0,N,0,0.3,8.8
1048560,1048560,1,231.0,246.0,2.05,0.5,2.10,04/05/2017 02:52:01 PM,04/05/2017 03:01:19 PM,1.0,0,1.0,1.0,N,0,0.3,12.35
1048561,1048561,2,234.0,100.0,1.5,0.5,1.29,04/07/2017 09:49:38 AM,04/07/2017 10:01:45 AM,5.0,0,1.0,1.0,N,0,0.3,11.3
1048562,1048562,1,141.0,162.0,1.75,0.5,1.20,04/06/2017 07:35:58 AM,04/06/2017 07:45:26 AM,1.0,0,1.0,1.0,N,0,0.3,10.55
1048563,1048563,1,243.0,41.0,3.2,0.5,3.70,04/03/2017 09:22:18 PM,04/03/2017 09:47:56 PM,1.0,0,1.0,1.0,N,0.5,0.3,23
1048564,1048564,2,132.0,230.0,13,0.5,17.29,04/03/2017 07:01:00 PM,04/03/2017 07:32:40 PM,2.0,5.76,1.0,2.0,N,4.5,0.3,76.06
1048565,1048565,2,41.0,166.0,0,0.5,0.99,04/05/2017 11:27:40 AM,04/05/2017 11:34:20 AM,1.0,0,2.0,1.0,N,0,0.3,7.3
1048566,1048566,1,186.0,1.0,16,0,16.20,04/03/2017 11:43:23 AM,04/03/2017 12:19:06 PM,1.0,16.5,1.0,3.0,N,0,0.3,96.3
1048567,1048567,2,236.0,162.0,1.66,0.5,1.12,04/06/2017 07:53:04 PM,04/06/2017 07:58:47 PM,1.0,0,1.0,1.0,N,1,0.3,9.96
1048568,1048568,2,161.0,162.0,0,0.5,0.70,04/05/2017 12:34:53 AM,04/05/2017 12:38:12 AM,1.0,0,2.0,1.0,N,0.5,0.3,5.8
1048569,1048569,1,138.0,230.0,0,0.5,10.40,04/06/2017 02:43:38 PM,04/06/2017 03:29:40 PM,1.0,5.76,2.0,1.0,N,0,0.3,43.56
1048570,1048570,1,48.0,50.0,1,0.5,1.40,04/06/2017 11:17:09 PM,04/06/2017 11:25:04 PM,1.0,0,1.0,1.0,N,0.5,0.3,9.8
1048571,1048571,1,237.0,166.0,0,0.5,3.60,04/06/2017 10:58:47 AM,04/06/2017 11:22:04 AM,1.0,0,2.0,1.0,N,0,0.3,18.3
1048572,1048572,1,164.0,90.0,2.35,0.5,1.70,04/06/2017 10:03:42 PM,04/06/2017 10:17:04 PM,1.0,0,1.0,1.0,N,0.5,0.3,14.15
1048573,1048573,2,264.0,264.0,0,0.5,1.80,04/06/2017 06:43:22 PM,04/06/2017 06:56:09 PM,4.0,0,2.0,1.0,N,1,0.3,11.8
1048574,1048574,1,74.0,74.0,0,0.5,0.30,04/04/2017 07:45:03 AM,04/04/2017 07:47:49 AM,1.0,0,2.0,1.0,N,0,0.3,4.8

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 17 columns):
ID                        1048575 non-null int64
vendor+AF8-id             1048575 non-null object
pickup+AF8-loc            1048574 non-null float64
drop+AF8-loc              1048574 non-null float64
driver+AF8-tip            1048573 non-null object
mta+AF8-tax               1048574 non-null object
distance                  1048574 non-null float64
pickup+AF8-time           1048574 non-null object
drop+AF8-time             1048574 non-null object
num+AF8-passengers        1048574 non-null float64
toll+AF8-amount           1048573 non-null object
payment+AF8-method        1048574 non-null float64
rate+AF8-code             1048574 non-null float64
stored+AF8-flag           1048574 non-null object
extra+AF8-charges         1048574 non-null object
improvement+AF8-charge    1048573 non-null object
total+AF8-amount          1048573 non-null object
dtypes: float64(6), int64(1), object(10)
memory usage: 136.0+ MB

In [10]:
train.head(10)

,ID,vendor+AF8-id,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,pickup+AF8-time,drop+AF8-time,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,stored+AF8-flag,extra+AF8-charges,improvement+AF8-charge,total+AF8-amount
0,0,1,170.0,233.0,1.83,0.5,0.70,04/04/2017 05:59:43 PM,04/04/2017 06:05:04 PM,1.0,0,1.0,1.0,N,1,0.3,9.13
1,1,2,151.0,243.0,3.56,0.5,4.64,04/03/2017 07:03:34 PM,04/03/2017 07:20:04 PM,1.0,0,1.0,1.0,N,1,0.3,21.36
2,2,2,68.0,90.0,1.5,0.5,1.29,04/03/2017 03:06:13 PM,04/03/2017 03:12:30 PM,2.0,0,1.0,1.0,N,0,0.3,8.8
3,3,2,142.0,234.0,1.5,0.5,2.74,04/04/2017 08:10:52 AM,04/04/2017 08:27:00 AM,1.0,0,1.0,1.0,N,0,0.3,14.8
4,4,2,238.0,238.0,0,0.5,0.45,04/05/2017 02:02:59 PM,04/05/2017 02:05:41 PM,6.0,0,2.0,1.0,N,0,0.3,4.8
5,5,1,230.0,48.0,1.05,0.5,0.40,04/03/2017 09:10:13 AM,04/03/2017 09:12:09 AM,1.0,0,1.0,1.0,N,0,0.3,5.35
6,6,2,236.0,140.0,2.46,0.5,1.72,04/03/2017 12:04:52 PM,04/03/2017 12:20:54 PM,3.0,0,1.0,1.0,N,0,0.3,14.76
7,7,1,236.0,13.0,5.95,0.5,8.80,04/04/2017 03:19:38 PM,04/04/2017 03:48:18 PM,1.0,0,1.0,1.0,N,0,0.3,35.75
8,8,1,229.0,141.0,0,0.5,1.20,04/05/2017 09:16:22 PM,04/05/2017 09:24:26 PM,2.0,0,2.0,1.0,N,0.5,0.3,8.8
9,9,1,132.0,164.0,0,0.5,17.00,04/06/2017 07:38:53 PM,04/06/2017 08:17:01 PM,2.0,5.76,2.0,2.0,N,4.5,0.3,63.06

In [11]:
train.shape

(1048575, 17)

In [12]:
train.columns

Index(['ID', 'vendor+AF8-id', 'pickup+AF8-loc', 'drop+AF8-loc',
       'driver+AF8-tip', 'mta+AF8-tax', 'distance', 'pickup+AF8-time',
       'drop+AF8-time', 'num+AF8-passengers', 'toll+AF8-amount',
       'payment+AF8-method', 'rate+AF8-code', 'stored+AF8-flag',
       'extra+AF8-charges', 'improvement+AF8-charge', 'total+AF8-amount'],
      dtype='object')

In [13]:
train.isnull().sum()

ID                        0
vendor+AF8-id             0
pickup+AF8-loc            1
drop+AF8-loc              1
driver+AF8-tip            2
mta+AF8-tax               1
distance                  1
pickup+AF8-time           1
drop+AF8-time             1
num+AF8-passengers        1
toll+AF8-amount           2
payment+AF8-method        1
rate+AF8-code             1
stored+AF8-flag           1
extra+AF8-charges         1
improvement+AF8-charge    2
total+AF8-amount          2
dtype: int64

In [14]:
test.isnull().sum()

ID                    0
vendor_id             0
pickup_loc            0
drop_loc              0
driver_tip            0
mta_tax               0
distance              0
pickup_time           0
drop_time             0
num_passengers        0
toll_amount           0
payment_method        0
rate_code             0
stored_flag           0
extra_charges         0
improvement_charge    0
dtype: int64

In [15]:
test.shape

(154235, 16)

In [16]:
train=train.astype({"vendor+AF8-id":"str"})

In [19]:
train=train.astype({"vendor+AF8-id":"float"})

In [18]:
train["vendor+AF8-id"][599121]="2"

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

# important cells to detect which rows are empty in a column

In [96]:
null_columns=train_copy.columns[train.isnull().any()]

In [97]:
train_copy[train_copy["driver+AF8-tip"].isnull()][null_columns]

Empty DataFrame
Columns: [pickup+AF8-loc, drop+AF8-loc, driver+AF8-tip, mta+AF8-tax, distance, pickup+AF8-time, drop+AF8-time, num+AF8-passengers, toll+AF8-amount, payment+AF8-method, rate+AF8-code, stored+AF8-flag, extra+AF8-charges, improvement+AF8-charge, total+AF8-amount]
Index: []

In [98]:
s=pd.Series(train_copy["driver+AF8-tip"])

# important cell

In [100]:
s=pd.to_numeric(s, errors='coerce')

In [101]:
train_copy["driver+AF8-tip"]=s

In [102]:
train_copy[train_copy["driver+AF8-tip"].isnull()][null_columns]

,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,pickup+AF8-time,drop+AF8-time,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,stored+AF8-flag,extra+AF8-charges,improvement+AF8-charge,total+AF8-amount
20373,193.0,193.0,NaN,+AC0-0.5,0.00,04/07/2017 04:21:04 AM,04/07/2017 04:21:10 AM,1.0,0,3.0,1.0,N,+AC0-0.5,+AC0-0.3,+AC0-4.94
82413,152.0,152.0,NaN,+AC0-0.5,0.00,04/04/2017 09:18:05 AM,04/04/2017 09:18:18 AM,3.0,0,3.0,1.0,N,0,+AC0-0.3,+AC0-3.96
102562,152.0,152.0,NaN,+AC0-0.5,0.00,04/03/2017 08:36:45 AM,04/03/2017 08:36:50 AM,1.0,0,3.0,1.0,N,0,+AC0-0.3,+AC0-3.96
161815,238.0,239.0,NaN,+AC0-0.5,0.66,04/06/2017 11:33:54 PM,04/06/2017 11:37:12 PM,1.0,0,4.0,1.0,N,+AC0-0.5,+AC0-0.3,+AC0-15.89
185987,193.0,193.0,NaN,+AC0-0.5,0.00,04/06/2017 03:47:29 AM,04/06/2017 03:47:46 AM,1.0,0,3.0,1.0,N,+AC0-0.5,+AC0-0.3,+AC0-4.94
256433,193.0,193.0,NaN,+AC0-0.5,0.00,04/06/2017 03:50:01 AM,04/06/2017 03:50:04 AM,2.0,0,3.0,1.0,N,+AC0-0.5,+AC0-0.3,+AC0-4.94
293271,264.0,193.0,NaN,+AC0-0.5,0.00,04/06/2017 04:08:16 AM,04/06/2017 04:08:57 AM,1.0,0,3.0,1.0,N,+AC0-0.5,+AC0-0.3,+AC0-4.94
385441,161.0,163.0,NaN,+AC0-0.5,0.19,04/04/2017 03:16:34 PM,04/04/2017 03:19:03 PM,2.0,0,3.0,1.0,N,0,+AC0-0.3,+AC0-5.59
468777,264.0,193.0,NaN,+AC0-0.5,0.00,04/06/2017 03:48:45 AM,04/06/2017 03:48:49 AM,2.0,0,3.0,1.0,N,+AC0-0.5,+AC0-0.3,+AC0-4.94
979065,152.0,152.0,NaN,+AC0-0.5,0.00,04/05/2017 07:06:49 PM,04/05/2017 07:07:00 PM,2.0,0,3.0,1.0,N,+AC0-1,+AC0-0.3,+AC0-5.16
1002440,65.0,264.0,NaN,+AC0-0.5,0.01,04/03/2017 11:13:07 AM,04/03/2017 11:13:16 AM,1.0,0,3.0,2.0,N,0,+AC0-0.3,+AC0-62.67
1021197,193.0,193.0,NaN,+AC0-0.5,0.00,04/05/2017 10:36:40 AM,04/05/2017 10:36:46 AM,4.0,0,3.0,1.0,N,0,+AC0-0.3,+AC0-3.96

In [103]:
s=pd.Series(train_copy["driver+AF8-tip"])

In [104]:
s

0           1.83
1           3.56
2           1.50
3           1.50
4           0.00
5           1.05
6           2.46
7           5.95
8           0.00
9           0.00
10          2.58
11          1.25
12          1.30
13          2.65
14          1.55
15          0.00
16          0.00
17          0.00
18          1.00
19          0.00
20          1.00
21          4.00
22          0.95
23          3.00
24          1.03
25          1.96
26          4.00
27          2.82
28          0.00
29          0.22
           ...
1048545     3.96
1048546     3.50
1048547     2.20
1048548     0.79
1048549     1.15
1048550     1.89
1048551     0.00
1048552     0.00
1048553     1.56
1048554     0.00
1048555     2.35
1048556     0.00
1048557     1.16
1048558     1.36
1048559     1.00
1048560     2.05
1048561     1.50
1048562     1.75
1048563     3.20
1048564    13.00
1048565     0.00
1048566    16.00
1048567     1.66
1048568     0.00
1048569     0.00
1048570     1.00
1048571     0.00
1048572     2.35
1048573     0.00
1048574     0.00
Name: driver+AF8-tip, Length: 1048573, dtype: float64

# important cells

In [106]:
train_copy=train_copy.astype({"driver+AF8-tip":"str"})

In [107]:
train_copy=train_copy.astype({"driver+AF8-tip":"float"})

In [108]:
mean=train_copy["driver+AF8-tip"].mean()

In [109]:
train_copy["driver+AF8-tip"]=train_copy["driver+AF8-tip"].fillna(mean)

In [110]:
train_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1048573 entries, 0 to 1048574
Data columns (total 17 columns):
ID                        1048573 non-null int64
vendor+AF8-id             1048573 non-null float64
pickup+AF8-loc            1048573 non-null float64
drop+AF8-loc              1048573 non-null float64
driver+AF8-tip            1048573 non-null float64
mta+AF8-tax               1048573 non-null object
distance                  1048573 non-null float64
pickup+AF8-time           1048573 non-null object
drop+AF8-time             1048573 non-null object
num+AF8-passengers        1048573 non-null float64
toll+AF8-amount           1048573 non-null object
payment+AF8-method        1048573 non-null float64
rate+AF8-code             1048573 non-null float64
stored+AF8-flag           1048573 non-null object
extra+AF8-charges         1048573 non-null object
improvement+AF8-charge    1048573 non-null object
total+AF8-amount          1048573 non-null object
dtypes: float64(8), int64(1), object(8)
memory usage: 144.0+ MB

In [129]:
train_copy.head(20)

,ID,vendor+AF8-id,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,pickup+AF8-time,drop+AF8-time,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,extra+AF8-charges,improvement+AF8-charge,total+AF8-amount,flag_N,flag_Y,flag_N,flag_Y
0,0,1.0,170.0,233.0,1.83,0.5,0.70,04/04/2017 05:59:43 PM,04/04/2017 06:05:04 PM,1.0,0.00,1.0,1.0,1.0,0.3,9.13,1,0,1,0
1,1,2.0,151.0,243.0,3.56,0.5,4.64,04/03/2017 07:03:34 PM,04/03/2017 07:20:04 PM,1.0,0.00,1.0,1.0,1.0,0.3,21.36,1,0,1,0
2,2,2.0,68.0,90.0,1.50,0.5,1.29,04/03/2017 03:06:13 PM,04/03/2017 03:12:30 PM,2.0,0.00,1.0,1.0,0.0,0.3,8.8,1,0,1,0
3,3,2.0,142.0,234.0,1.50,0.5,2.74,04/04/2017 08:10:52 AM,04/04/2017 08:27:00 AM,1.0,0.00,1.0,1.0,0.0,0.3,14.8,1,0,1,0
4,4,2.0,238.0,238.0,0.00,0.5,0.45,04/05/2017 02:02:59 PM,04/05/2017 02:05:41 PM,6.0,0.00,2.0,1.0,0.0,0.3,4.8,1,0,1,0
5,5,1.0,230.0,48.0,1.05,0.5,0.40,04/03/2017 09:10:13 AM,04/03/2017 09:12:09 AM,1.0,0.00,1.0,1.0,0.0,0.3,5.35,1,0,1,0
6,6,2.0,236.0,140.0,2.46,0.5,1.72,04/03/2017 12:04:52 PM,04/03/2017 12:20:54 PM,3.0,0.00,1.0,1.0,0.0,0.3,14.76,1,0,1,0
7,7,1.0,236.0,13.0,5.95,0.5,8.80,04/04/2017 03:19:38 PM,04/04/2017 03:48:18 PM,1.0,0.00,1.0,1.0,0.0,0.3,35.75,1,0,1,0
8,8,1.0,229.0,141.0,0.00,0.5,1.20,04/05/2017 09:16:22 PM,04/05/2017 09:24:26 PM,2.0,0.00,2.0,1.0,0.5,0.3,8.8,1,0,1,0
9,9,1.0,132.0,164.0,0.00,0.5,17.00,04/06/2017 07:38:53 PM,04/06/2017 08:17:01 PM,2.0,5.76,2.0,2.0,4.5,0.3,63.06,1,0,1,0
10,10,2.0,114.0,170.0,2.58,0.5,1.54,04/06/2017 06:05:00 PM,04/06/2017 06:15:30 PM,1.0,0.00,1.0,1.0,1.0,0.3,12.88,1,0,1,0
11,11,1.0,264.0,264.0,1.25,0.5,0.70,04/06/2017 08:13:58 PM,04/06/2017 08:18:25 PM,1.0,0.00,1.0,1.0,0.5,0.3,7.55,1,0,1,0
12,12,2.0,238.0,151.0,1.30,0.5,0.59,04/03/2017 04:04:51 PM,04/03/2017 04:10:30 PM,1.0,0.00,1.0,1.0,1.0,0.3,8.6,1,0,1,0
13,13,1.0,170.0,246.0,2.65,0.5,1.90,04/04/2017 08:13:50 AM,04/04/2017 08:30:44 AM,1.0,0.00,1.0,1.0,0.0,0.3,15.95,1,0,1,0
14,14,1.0,166.0,238.0,1.55,0.5,1.30,04/03/2017 05:14:57 PM,04/03/2017 05:19:39 PM,1.0,0.00,1.0,1.0,1.0,0.3,9.35,1,0,1,0
15,15,2.0,263.0,138.0,0.00,0.5,6.95,04/07/2017 09:32:20 AM,04/07/2017 09:51:05 AM,1.0,5.76,1.0,1.0,0.0,0.3,29.06,1,0,1,0
16,16,2.0,137.0,79.0,0.00,0.5,1.17,04/06/2017 09:42:34 PM,04/06/2017 09:48:39 PM,1.0,0.00,2.0,1.0,0.5,0.3,7.8,1,0,1,0
17,17,1.0,90.0,230.0,0.00,0.5,1.60,04/05/2017 08:26:54 AM,04/05/2017 08:39:18 AM,1.0,0.00,2.0,1.0,0.0,0.3,10.3,1,0,1,0
18,18,2.0,141.0,263.0,1.00,0.5,1.00,04/05/2017 04:06:52 PM,04/05/2017 04:11:23 PM,1.0,0.00,1.0,1.0,1.0,0.3,8.3,1,0,1,0
19,19,1.0,264.0,264.0,0.00,0.5,2.20,04/03/2017 08:52:11 AM,04/03/2017 09:05:20 AM,1.0,0.00,2.0,1.0,0.0,0.3,11.8,1,0,1,0

In [112]:
def change(s):
    ser=pd.Series(s)
    ser=pd.to_numeric(ser,errors="coerce")
    mean=ser.mean()
    ser=ser.fillna(mean)
    return ser

In [113]:
train_copy["mta+AF8-tax"]=change(train_copy["mta+AF8-tax"])

In [136]:
train_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1048573 entries, 0 to 1048574
Data columns (total 18 columns):
ID                        1048573 non-null int64
vendor+AF8-id             1048573 non-null float64
pickup+AF8-loc            1048573 non-null float64
drop+AF8-loc              1048573 non-null float64
driver+AF8-tip            1048573 non-null float64
mta+AF8-tax               1048573 non-null float64
distance                  1048573 non-null float64
pickup+AF8-time           1048573 non-null object
drop+AF8-time             1048573 non-null object
num+AF8-passengers        1048573 non-null float64
toll+AF8-amount           1048573 non-null float64
payment+AF8-method        1048573 non-null float64
rate+AF8-code             1048573 non-null float64
extra+AF8-charges         1048573 non-null float64
improvement+AF8-charge    1048573 non-null object
total+AF8-amount          1048573 non-null object
flag_N                    1048573 non-null uint8
flag_Y                    1048573 non-null uint8
dtypes: float64(11), int64(1), object(4), uint8(2)
memory usage: 138.0+ MB

In [115]:
train_copy=train_copy.astype({"mta+AF8-tax":"float"})

In [116]:
train_copy["toll+AF8-amount"]=change(train_copy["toll+AF8-amount"])

In [117]:
train_copy=train_copy.astype({"toll+AF8-amount":"float"})

In [122]:
train_copy["extra+AF8-charges"]=change(train_copy["extra+AF8-charges"])

In [123]:
train_copy=train_copy.astype({"extra+AF8-charges":"float"})

In [119]:
train_copy["stored+AF8-flag"].value_counts()

N    1041404
Y       7169
Name: stored+AF8-flag, dtype: int64

In [124]:
train_copy["extra+AF8-charges"].value_counts()

0.000000    573701
0.500000    267377
1.000000    202414
4.500000      4847
0.341422       224
1.800000         3
0.050000         1
6.500000         1
1.500000         1
0.200000         1
0.100000         1
0.800000         1
1.300000         1
Name: extra+AF8-charges, dtype: int64

In [127]:
train_copy= pd.concat([train_copy,pd.get_dummies(train_copy['stored+AF8-flag'], prefix='flag')],axis=1)
train_copy.drop(['stored+AF8-flag'],axis=1,inplace=True)

In [358]:
test_copy=test

In [363]:
test_copy= pd.concat([test_copy,pd.get_dummies(test_copy['stored_flag'], prefix='flag')],axis=1)
test_copy.drop(['stored_flag'],axis=1,inplace=True)

In [131]:
train_min=train_copy.drop(["flag_N"],axis=1)

In [168]:
train_min.head(30)

,ID,vendor+AF8-id,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,pickup+AF8-time,drop+AF8-time,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,extra+AF8-charges,improvement+AF8-charge,total+AF8-amount,flag_Y,flag_Y
0,0,1.0,170.0,233.0,1.83,0.5,0.70,04/04/2017 05:59:43 PM,04/04/2017 06:05:04 PM,1.0,0.00,1.0,1.0,1.0,0.3,9.13,0,0
1,1,2.0,151.0,243.0,3.56,0.5,4.64,04/03/2017 07:03:34 PM,04/03/2017 07:20:04 PM,1.0,0.00,1.0,1.0,1.0,0.3,21.36,0,0
2,2,2.0,68.0,90.0,1.50,0.5,1.29,04/03/2017 03:06:13 PM,04/03/2017 03:12:30 PM,2.0,0.00,1.0,1.0,0.0,0.3,8.8,0,0
3,3,2.0,142.0,234.0,1.50,0.5,2.74,04/04/2017 08:10:52 AM,04/04/2017 08:27:00 AM,1.0,0.00,1.0,1.0,0.0,0.3,14.8,0,0
4,4,2.0,238.0,238.0,0.00,0.5,0.45,04/05/2017 02:02:59 PM,04/05/2017 02:05:41 PM,6.0,0.00,2.0,1.0,0.0,0.3,4.8,0,0
5,5,1.0,230.0,48.0,1.05,0.5,0.40,04/03/2017 09:10:13 AM,04/03/2017 09:12:09 AM,1.0,0.00,1.0,1.0,0.0,0.3,5.35,0,0
6,6,2.0,236.0,140.0,2.46,0.5,1.72,04/03/2017 12:04:52 PM,04/03/2017 12:20:54 PM,3.0,0.00,1.0,1.0,0.0,0.3,14.76,0,0
7,7,1.0,236.0,13.0,5.95,0.5,8.80,04/04/2017 03:19:38 PM,04/04/2017 03:48:18 PM,1.0,0.00,1.0,1.0,0.0,0.3,35.75,0,0
8,8,1.0,229.0,141.0,0.00,0.5,1.20,04/05/2017 09:16:22 PM,04/05/2017 09:24:26 PM,2.0,0.00,2.0,1.0,0.5,0.3,8.8,0,0
9,9,1.0,132.0,164.0,0.00,0.5,17.00,04/06/2017 07:38:53 PM,04/06/2017 08:17:01 PM,2.0,5.76,2.0,2.0,4.5,0.3,63.06,0,0
10,10,2.0,114.0,170.0,2.58,0.5,1.54,04/06/2017 06:05:00 PM,04/06/2017 06:15:30 PM,1.0,0.00,1.0,1.0,1.0,0.3,12.88,0,0
11,11,1.0,264.0,264.0,1.25,0.5,0.70,04/06/2017 08:13:58 PM,04/06/2017 08:18:25 PM,1.0,0.00,1.0,1.0,0.5,0.3,7.55,0,0
12,12,2.0,238.0,151.0,1.30,0.5,0.59,04/03/2017 04:04:51 PM,04/03/2017 04:10:30 PM,1.0,0.00,1.0,1.0,1.0,0.3,8.6,0,0
13,13,1.0,170.0,246.0,2.65,0.5,1.90,04/04/2017 08:13:50 AM,04/04/2017 08:30:44 AM,1.0,0.00,1.0,1.0,0.0,0.3,15.95,0,0
14,14,1.0,166.0,238.0,1.55,0.5,1.30,04/03/2017 05:14:57 PM,04/03/2017 05:19:39 PM,1.0,0.00,1.0,1.0,1.0,0.3,9.35,0,0
15,15,2.0,263.0,138.0,0.00,0.5,6.95,04/07/2017 09:32:20 AM,04/07/2017 09:51:05 AM,1.0,5.76,1.0,1.0,0.0,0.3,29.06,0,0
16,16,2.0,137.0,79.0,0.00,0.5,1.17,04/06/2017 09:42:34 PM,04/06/2017 09:48:39 PM,1.0,0.00,2.0,1.0,0.5,0.3,7.8,0,0
17,17,1.0,90.0,230.0,0.00,0.5,1.60,04/05/2017 08:26:54 AM,04/05/2017 08:39:18 AM,1.0,0.00,2.0,1.0,0.0,0.3,10.3,0,0
18,18,2.0,141.0,263.0,1.00,0.5,1.00,04/05/2017 04:06:52 PM,04/05/2017 04:11:23 PM,1.0,0.00,1.0,1.0,1.0,0.3,8.3,0,0
19,19,1.0,264.0,264.0,0.00,0.5,2.20,04/03/2017 08:52:11 AM,04/03/2017 09:05:20 AM,1.0,0.00,2.0,1.0,0.0,0.3,11.8,0,0
20,20,2.0,211.0,90.0,1.00,0.5,1.73,04/03/2017 05:30:54 PM,04/03/2017 05:41:11 PM,1.0,0.00,1.0,1.0,1.0,0.3,11.3,0,0
21,21,2.0,138.0,232.0,4.00,0.5,8.92,04/06/2017 01:41:14 PM,04/06/2017 02:08:36 PM,3.0,5.54,1.0,1.0,0.0,0.3,38.84,0,0
22,22,1.0,164.0,170.0,0.95,0.5,0.40,04/06/2017 06:57:09 AM,04/06/2017 07:00:01 AM,1.0,0.00,1.0,1.0,0.0,0.3,5.75,0,0
23,23,1.0,141.0,170.0,3.00,0.5,2.30,04/07/2017 01:46:13 PM,04/07/2017 02:00:29 PM,1.0,0.00,1.0,1.0,0.0,0.3,15.3,0,0
24,24,1.0,68.0,143.0,1.03,0.5,1.90,04/04/2017 04:34:12 PM,04/04/2017 04:43:26 PM,1.0,0.00,1.0,1.0,1.0,0.3,11.33,0,0
25,25,2.0,148.0,79.0,1.96,0.5,1.17,04/05/2017 07:04:52 PM,04/05/2017 07:14:41 PM,2.0,0.00,1.0,1.0,1.0,0.3,11.76,0,0
26,26,1.0,138.0,229.0,4.00,0.5,9.90,04/07/2017 02:50:34 PM,04/07/2017 03:18:40 PM,1.0,5.76,1.0,1.0,0.0,0.3,40.06,0,0
27,27,2.0,237.0,170.0,2.82,0.5,0.89,04/06/2017 09:35:09 AM,04/06/2017 09:51:52 AM,2.0,0.00,1.0,1.0,0.0,0.3,14.12,0,0
28,28,2.0,261.0,164.0,0.00,0.5,4.60,04/06/2017 04:16:23 PM,04/06/2017 05:01:32 PM,4.0,0.00,2.0,1.0,1.0,0.3,29.3,0,0
29,29,1.0,236.0,50.0,0.22,0.5,2.60,04/04/2017 02:29:36 PM,04/04/2017 02:48:46 PM,1.0,0.00,1.0,1.0,0.0,0.3,15.02,0,0

In [134]:
train_copy=train_copy.loc[:,~train_copy.columns.duplicated()]

In [364]:
test_copy=test_copy.loc[:,~test_copy.columns.duplicated()]

# see cell above this. used to remove duplicate columns

In [365]:
test_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154235 entries, 0 to 154234
Data columns (total 17 columns):
ID                    154235 non-null int64
vendor_id             154235 non-null int64
pickup_loc            154235 non-null float64
drop_loc              154235 non-null float64
driver_tip            154235 non-null float64
mta_tax               154235 non-null float64
distance              154235 non-null float64
pickup_time           154235 non-null object
drop_time             154235 non-null object
num_passengers        154235 non-null float64
toll_amount           154235 non-null float64
payment_method        154235 non-null float64
rate_code             154235 non-null float64
extra_charges         154235 non-null float64
improvement_charge    154235 non-null float64
flag_N                154235 non-null uint8
flag_Y                154235 non-null uint8
dtypes: float64(11), int64(2), object(2), uint8(2)
memory usage: 17.9+ MB

In [257]:
train_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1048573 entries, 0 to 1048574
Data columns (total 18 columns):
ID                        1048573 non-null int64
vendor+AF8-id             1048573 non-null float64
pickup+AF8-loc            1048573 non-null float64
drop+AF8-loc              1048573 non-null float64
driver+AF8-tip            1048573 non-null float64
mta+AF8-tax               1048573 non-null float64
distance                  1048573 non-null float64
pickup+AF8-time           1048573 non-null datetime64[ns]
drop+AF8-time             1048573 non-null object
num+AF8-passengers        1048573 non-null float64
toll+AF8-amount           1048573 non-null float64
payment+AF8-method        1048573 non-null float64
rate+AF8-code             1048573 non-null float64
extra+AF8-charges         1048573 non-null float64
improvement+AF8-charge    1048573 non-null float64
total+AF8-amount          1048573 non-null float64
flag_N                    1048573 non-null uint8
flag_Y                    1048573 non-null uint8
dtypes: datetime64[ns](1), float64(13), int64(1), object(1), uint8(2)
memory usage: 138.0+ MB

In [139]:
train_copy["improvement+AF8-charge"]=change(train_copy["improvement+AF8-charge"])

In [140]:
train_copy=train_copy.astype({"improvement+AF8-charge":"float"})

In [142]:
train_copy["total+AF8-amount"]=change(train_copy["total+AF8-amount"])

In [143]:
train_copy=train_copy.astype({"total+AF8-amount":"float"})

In [145]:
from datetime import datetime

In [238]:
a=train_copy["drop+AF8-time"][36098]

In [239]:
pick=datetime.strptime(a,'%m/%d/%Y %H:%M:%S %p')

In [240]:
a

'04/05/2017 07:59:13 AM'

In [241]:
pick

datetime.datetime(2017, 4, 5, 7, 59, 13)

In [197]:
m=type(train_copy["drop+AF8-time"][100000])

In [200]:
m

str

In [173]:
drop=datetime.strptime(b,'%m/%d/%Y %H:%M:%S %p')

TypeError: strptime() argument 1 must be str, not datetime.datetime

In [162]:
drop

datetime.datetime(2017, 4, 3, 7, 20, 4)

In [175]:
delta=b-a

In [176]:
delta

datetime.timedelta(days=-2, seconds=321)

In [259]:
'''#j=36098
#for i in train_copy["drop+AF8-time"][36098:]:
    pick=datetime.strptime(i,'%m/%d/%Y %H:%M:%S %p')
    train_copy["drop+AF8-time"][j]=pick
    j=j+1 '''

'#j=36098\n#for i in train_copy["drop+AF8-time"][36098:]:\n    pick=datetime.strptime(i,\'%m/%d/%Y %H:%M:%S %p\')\n    train_copy["drop+AF8-time"][j]=pick\n    j=j+1 '

In [253]:
train_copy["drop+AF8-time"][36400]

datetime.datetime(2017, 4, 6, 10, 19, 38)

In [201]:
j=0;
for i in train_copy["pickup+AF8-time"]:
    if(type(i)=="datetime.datetime"):
        print(i)
        print(j)
        j=j+1

In [372]:
 train_copy["pickup+AF8-time"]=train_min["pickup+AF8-time"]

In [373]:
train_copy["drop+AF8-time"]=train_min["drop+AF8-time"]

In [374]:
train_copy["pickup+AF8-time"]= pd.to_datetime(train_copy["pickup+AF8-time"])

KeyboardInterrupt:

In [ ]:
train_copy["drop+AF8-time"]=pd.to_datetime(train_copy["drop+AF8-time"])

In [370]:
test_copy["pickup_time"]= pd.to_datetime(test_copy["pickup_time"])

In [371]:
test_copy["drop_time"]=pd.to_datetime(test_copy["drop_time"])

In [276]:
train_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1048573 entries, 0 to 1048574
Data columns (total 20 columns):
ID                        1048573 non-null int64
vendor+AF8-id             1048573 non-null float64
pickup+AF8-loc            1048573 non-null float64
drop+AF8-loc              1048573 non-null float64
driver+AF8-tip            1048573 non-null float64
mta+AF8-tax               1048573 non-null float64
distance                  1048573 non-null float64
pickup+AF8-time           1048573 non-null datetime64[ns]
drop+AF8-time             1048573 non-null datetime64[ns]
num+AF8-passengers        1048573 non-null float64
toll+AF8-amount           1048573 non-null float64
payment+AF8-method        1048573 non-null float64
rate+AF8-code             1048573 non-null float64
extra+AF8-charges         1048573 non-null float64
improvement+AF8-charge    1048573 non-null float64
total+AF8-amount          1048573 non-null float64
flag_N                    1048573 non-null uint8
flag_Y                    1048573 non-null uint8
delta                     1048573 non-null timedelta64[ns]
deltas                    1048573 non-null float64
dtypes: datetime64[ns](2), float64(14), int64(1), timedelta64[ns](1), uint8(2)
memory usage: 154.0 MB

In [375]:
test_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154235 entries, 0 to 154234
Data columns (total 17 columns):
ID                    154235 non-null int64
vendor_id             154235 non-null int64
pickup_loc            154235 non-null float64
drop_loc              154235 non-null float64
driver_tip            154235 non-null float64
mta_tax               154235 non-null float64
distance              154235 non-null float64
pickup_time           154235 non-null datetime64[ns]
drop_time             154235 non-null datetime64[ns]
num_passengers        154235 non-null float64
toll_amount           154235 non-null float64
payment_method        154235 non-null float64
rate_code             154235 non-null float64
extra_charges         154235 non-null float64
improvement_charge    154235 non-null float64
flag_N                154235 non-null uint8
flag_Y                154235 non-null uint8
dtypes: datetime64[ns](2), float64(11), int64(2), uint8(2)
memory usage: 17.9 MB

In [292]:
train_copy.head(20)

,ID,vendor+AF8-id,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,pickup+AF8-time,drop+AF8-time,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,extra+AF8-charges,improvement+AF8-charge,total+AF8-amount,flag_N,flag_Y,delta,deltas
0,0,1.0,170.0,233.0,1.83,0.5,0.70,2017-04-04 17:59:43,2017-04-04 18:05:04,1.0,0.00,1.0,1.0,1.0,0.3,9.13,1,0,00:05:21,321.0
1,1,2.0,151.0,243.0,3.56,0.5,4.64,2017-04-03 19:03:34,2017-04-03 19:20:04,1.0,0.00,1.0,1.0,1.0,0.3,21.36,1,0,00:16:30,990.0
2,2,2.0,68.0,90.0,1.50,0.5,1.29,2017-04-03 15:06:13,2017-04-03 15:12:30,2.0,0.00,1.0,1.0,0.0,0.3,8.80,1,0,00:06:17,377.0
3,3,2.0,142.0,234.0,1.50,0.5,2.74,2017-04-04 08:10:52,2017-04-04 08:27:00,1.0,0.00,1.0,1.0,0.0,0.3,14.80,1,0,00:16:08,968.0
4,4,2.0,238.0,238.0,0.00,0.5,0.45,2017-04-05 14:02:59,2017-04-05 14:05:41,6.0,0.00,2.0,1.0,0.0,0.3,4.80,1,0,00:02:42,162.0
5,5,1.0,230.0,48.0,1.05,0.5,0.40,2017-04-03 09:10:13,2017-04-03 09:12:09,1.0,0.00,1.0,1.0,0.0,0.3,5.35,1,0,00:01:56,116.0
6,6,2.0,236.0,140.0,2.46,0.5,1.72,2017-04-03 12:04:52,2017-04-03 12:20:54,3.0,0.00,1.0,1.0,0.0,0.3,14.76,1,0,00:16:02,962.0
7,7,1.0,236.0,13.0,5.95,0.5,8.80,2017-04-04 15:19:38,2017-04-04 15:48:18,1.0,0.00,1.0,1.0,0.0,0.3,35.75,1,0,00:28:40,1720.0
8,8,1.0,229.0,141.0,0.00,0.5,1.20,2017-04-05 21:16:22,2017-04-05 21:24:26,2.0,0.00,2.0,1.0,0.5,0.3,8.80,1,0,00:08:04,484.0
9,9,1.0,132.0,164.0,0.00,0.5,17.00,2017-04-06 19:38:53,2017-04-06 20:17:01,2.0,5.76,2.0,2.0,4.5,0.3,63.06,1,0,00:38:08,2288.0
10,10,2.0,114.0,170.0,2.58,0.5,1.54,2017-04-06 18:05:00,2017-04-06 18:15:30,1.0,0.00,1.0,1.0,1.0,0.3,12.88,1,0,00:10:30,630.0
11,11,1.0,264.0,264.0,1.25,0.5,0.70,2017-04-06 20:13:58,2017-04-06 20:18:25,1.0,0.00,1.0,1.0,0.5,0.3,7.55,1,0,00:04:27,267.0
12,12,2.0,238.0,151.0,1.30,0.5,0.59,2017-04-03 16:04:51,2017-04-03 16:10:30,1.0,0.00,1.0,1.0,1.0,0.3,8.60,1,0,00:05:39,339.0
13,13,1.0,170.0,246.0,2.65,0.5,1.90,2017-04-04 08:13:50,2017-04-04 08:30:44,1.0,0.00,1.0,1.0,0.0,0.3,15.95,1,0,00:16:54,1014.0
14,14,1.0,166.0,238.0,1.55,0.5,1.30,2017-04-03 17:14:57,2017-04-03 17:19:39,1.0,0.00,1.0,1.0,1.0,0.3,9.35,1,0,00:04:42,282.0
15,15,2.0,263.0,138.0,0.00,0.5,6.95,2017-04-07 09:32:20,2017-04-07 09:51:05,1.0,5.76,1.0,1.0,0.0,0.3,29.06,1,0,00:18:45,1125.0
16,16,2.0,137.0,79.0,0.00,0.5,1.17,2017-04-06 21:42:34,2017-04-06 21:48:39,1.0,0.00,2.0,1.0,0.5,0.3,7.80,1,0,00:06:05,365.0
17,17,1.0,90.0,230.0,0.00,0.5,1.60,2017-04-05 08:26:54,2017-04-05 08:39:18,1.0,0.00,2.0,1.0,0.0,0.3,10.30,1,0,00:12:24,744.0
18,18,2.0,141.0,263.0,1.00,0.5,1.00,2017-04-05 16:06:52,2017-04-05 16:11:23,1.0,0.00,1.0,1.0,1.0,0.3,8.30,1,0,00:04:31,271.0
19,19,1.0,264.0,264.0,0.00,0.5,2.20,2017-04-03 08:52:11,2017-04-03 09:05:20,1.0,0.00,2.0,1.0,0.0,0.3,11.80,1,0,00:13:09,789.0

In [271]:
train_copy["delta"]=train_copy["drop+AF8-time"]-train_copy["pickup+AF8-time"]

In [281]:
train_copy["deltas"]=train_copy["delta"].dt.total_seconds()

In [376]:
test_copy["delta"]=test_copy["drop_time"]-test_copy["pickup_time"]

In [377]:
test_copy["deltas"]=test_copy["delta"].dt.total_seconds()

In [274]:
'''j=0
for i in train_copy["delta"]:
    train_copy["deltas"][j]=i.seconds
    j=j+1'''

'j=0\nfor i in train_copy["delta"]:\n    train_copy["deltas"][j]=i.seconds\n    j=j+1'

In [291]:
j=0
max=train_copy["deltas"][0]
for i in train_copy["deltas"]:
    if(i>max):
        max=i
        p=j
        print(p)
        j=j+1
        pass
    else:
        continue

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14

In [285]:
train_copy["deltas"].max()

86386.0

In [290]:
train_copy["deltas"][14]

282.0

In [296]:
train_copy1=train_copy.drop(["drop+AF8-time","pickup+AF8-time","delta"],axis=1)

In [378]:
test_copy1=test_copy.drop(["pickup_time","drop_time","delta"],axis=1)

In [297]:
train_copy1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1048573 entries, 0 to 1048574
Data columns (total 17 columns):
ID                        1048573 non-null int64
vendor+AF8-id             1048573 non-null float64
pickup+AF8-loc            1048573 non-null float64
drop+AF8-loc              1048573 non-null float64
driver+AF8-tip            1048573 non-null float64
mta+AF8-tax               1048573 non-null float64
distance                  1048573 non-null float64
num+AF8-passengers        1048573 non-null float64
toll+AF8-amount           1048573 non-null float64
payment+AF8-method        1048573 non-null float64
rate+AF8-code             1048573 non-null float64
extra+AF8-charges         1048573 non-null float64
improvement+AF8-charge    1048573 non-null float64
total+AF8-amount          1048573 non-null float64
flag_N                    1048573 non-null uint8
flag_Y                    1048573 non-null uint8
deltas                    1048573 non-null float64
dtypes: float64(14), int64(1), uint8(2)
memory usage: 130.0 MB

In [298]:
target=train_copy1["total+AF8-amount"]
features=train_copy1.drop(["total+AF8-amount"],axis=1)

In [299]:
target

0           9.13
1          21.36
2           8.80
3          14.80
4           4.80
5           5.35
6          14.76
7          35.75
8           8.80
9          63.06
10         12.88
11          7.55
12          8.60
13         15.95
14          9.35
15         29.06
16          7.80
17         10.30
18          8.30
19         11.80
20         11.30
21         38.84
22          5.75
23         15.30
24         11.33
25         11.76
26         40.06
27         14.12
28         29.30
29         15.02
           ...
1048545    23.76
1048546    30.30
1048547    11.00
1048548     6.09
1048549     6.95
1048550     8.19
1048551     6.30
1048552    11.80
1048553     9.36
1048554     8.30
1048555    14.15
1048556     6.30
1048557     6.96
1048558     8.16
1048559     8.80
1048560    12.35
1048561    11.30
1048562    10.55
1048563    23.00
1048564    76.06
1048565     7.30
1048566    96.30
1048567     9.96
1048568     5.80
1048569    43.56
1048570     9.80
1048571    18.30
1048572    14.15
1048573    11.80
1048574     4.80
Name: total+AF8-amount, Length: 1048573, dtype: float64

In [300]:
features

,ID,vendor+AF8-id,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,extra+AF8-charges,improvement+AF8-charge,flag_N,flag_Y,deltas
0,0,1.0,170.0,233.0,1.83,0.5,0.70,1.0,0.00,1.0,1.0,1.0,0.3,1,0,321.0
1,1,2.0,151.0,243.0,3.56,0.5,4.64,1.0,0.00,1.0,1.0,1.0,0.3,1,0,990.0
2,2,2.0,68.0,90.0,1.50,0.5,1.29,2.0,0.00,1.0,1.0,0.0,0.3,1,0,377.0
3,3,2.0,142.0,234.0,1.50,0.5,2.74,1.0,0.00,1.0,1.0,0.0,0.3,1,0,968.0
4,4,2.0,238.0,238.0,0.00,0.5,0.45,6.0,0.00,2.0,1.0,0.0,0.3,1,0,162.0
5,5,1.0,230.0,48.0,1.05,0.5,0.40,1.0,0.00,1.0,1.0,0.0,0.3,1,0,116.0
6,6,2.0,236.0,140.0,2.46,0.5,1.72,3.0,0.00,1.0,1.0,0.0,0.3,1,0,962.0
7,7,1.0,236.0,13.0,5.95,0.5,8.80,1.0,0.00,1.0,1.0,0.0,0.3,1,0,1720.0
8,8,1.0,229.0,141.0,0.00,0.5,1.20,2.0,0.00,2.0,1.0,0.5,0.3,1,0,484.0
9,9,1.0,132.0,164.0,0.00,0.5,17.00,2.0,5.76,2.0,2.0,4.5,0.3,1,0,2288.0
10,10,2.0,114.0,170.0,2.58,0.5,1.54,1.0,0.00,1.0,1.0,1.0,0.3,1,0,630.0
11,11,1.0,264.0,264.0,1.25,0.5,0.70,1.0,0.00,1.0,1.0,0.5,0.3,1,0,267.0
12,12,2.0,238.0,151.0,1.30,0.5,0.59,1.0,0.00,1.0,1.0,1.0,0.3,1,0,339.0
13,13,1.0,170.0,246.0,2.65,0.5,1.90,1.0,0.00,1.0,1.0,0.0,0.3,1,0,1014.0
14,14,1.0,166.0,238.0,1.55,0.5,1.30,1.0,0.00,1.0,1.0,1.0,0.3,1,0,282.0
15,15,2.0,263.0,138.0,0.00,0.5,6.95,1.0,5.76,1.0,1.0,0.0,0.3,1,0,1125.0
16,16,2.0,137.0,79.0,0.00,0.5,1.17,1.0,0.00,2.0,1.0,0.5,0.3,1,0,365.0
17,17,1.0,90.0,230.0,0.00,0.5,1.60,1.0,0.00,2.0,1.0,0.0,0.3,1,0,744.0
18,18,2.0,141.0,263.0,1.00,0.5,1.00,1.0,0.00,1.0,1.0,1.0,0.3,1,0,271.0
19,19,1.0,264.0,264.0,0.00,0.5,2.20,1.0,0.00,2.0,1.0,0.0,0.3,1,0,789.0
20,20,2.0,211.0,90.0,1.00,0.5,1.73,1.0,0.00,1.0,1.0,1.0,0.3,1,0,617.0
21,21,2.0,138.0,232.0,4.00,0.5,8.92,3.0,5.54,1.0,1.0,0.0,0.3,1,0,1642.0
22,22,1.0,164.0,170.0,0.95,0.5,0.40,1.0,0.00,1.0,1.0,0.0,0.3,1,0,172.0
23,23,1.0,141.0,170.0,3.00,0.5,2.30,1.0,0.00,1.0,1.0,0.0,0.3,1,0,856.0
24,24,1.0,68.0,143.0,1.03,0.5,1.90,1.0,0.00,1.0,1.0,1.0,0.3,1,0,554.0
25,25,2.0,148.0,79.0,1.96,0.5,1.17,2.0,0.00,1.0,1.0,1.0,0.3,1,0,589.0
26,26,1.0,138.0,229.0,4.00,0.5,9.90,1.0,5.76,1.0,1.0,0.0,0.3,1,0,1686.0
27,27,2.0,237.0,170.0,2.82,0.5,0.89,2.0,0.00,1.0,1.0,0.0,0.3,1,0,1003.0
28,28,2.0,261.0,164.0,0.00,0.5,4.60,4.0,0.00,2.0,1.0,1.0,0.3,1,0,2709.0
29,29,1.0,236.0,50.0,0.22,0.5,2.60,1.0,0.00,1.0,1.0,0.0,0.3,1,0,1150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048545,1048545,2.0,186.0,236.0,3.96,0.5,3.85,1.0,0.00,1.0,1.0,0.0,0.3,1,0,1561.0
1048546,1048546,2.0,238.0,113.0,3.50,0.5,6.45,2.0,0.00,1.0,1.0,0.0,0.3,1,0,2247.0
1048547,1048547,1.0,143.0,50.0,2.20,0.5,0.90,1.0,0.00,1.0,1.0,0.0,0.3,1,0,635.0
1048548,1048548,1.0,263.0,263.0,0.79,0.5,0.40,1.0,0.00,1.0,1.0,1.0,0.3,1,0,130.0
1048549,1048549,1.0,113.0,79.0,1.15,0.5,0.50,1.0,0.00,1.0,1.0,0.5,0.3,1,0,267.0
1048550,1048550,2.0,237.0,237.0,1.89,0.5,0.69,1.0,0.00,1.0,1.0,0.0,0.3,1,0,333.0
1048551,1048551,1.0,234.0,186.0,0.00,0.5,0.90,1.0,0.00,2.0,1.0,0.5,0.3,1,0,279.0
1048552,1048552,2.0,142.0,141.0,0.00,0.5,1.37,1.0,0.00,2.0,1.0,0.0,0.3,1,0,956.0
1048553,1048553,2.0,113.0,79.0,1.56,0.5,0.93,2.0,0.00,1.0,1.0,0.5,0.3,1,0,465.0
1048554,1048554,2.0,48.0,161.0,0.00,0.5,1.04,3.0,0.00,2.0,1.0,0.0,0.3,1,0,561.0
1048555,1048555,1.0,107.0,230.0,2.35,0.5,2.40,1.0,0.00,1.0,1.0,0.5,0.3,1,0,697.0
1048556,1048556,1.0,164.0,161.0,0.00,0.5,1.00,1.0,0.00,2.0,1.0,0.0,0.3,1,0,314.0
1048557,1048557,2.0,237.0,237.0,1.16,0.5,0.67,1.0,0.00,1.0,1.0,0.0,0.3,1,0,288.0
1048558,1048558,2.0,239.0,142.0,1.36,0.5,0.59,1.0,0.00,1.0,1.0,1.0,0.3,1,0,277.0
1048559,1048559,2.0,90.0,125.0,1.00,0.5,1.31,1.0,0.00,1.0,1.0,0.0,0.3,1,0,458.0
1048560,1048560,1.0,231.0,246.0,2.05,0.5,2.10,1.0,0.00,1.0,1.0,0.0,0.3,1,0,558.0
1048561,1048561,2.0,234.0,100.0,1.50,0.5,1.29,5.0,0.00,1.0,1.0,0.0,0.3,1,0,727.0
1048562,1048562,1.0,141.0,162.0,1.75,0.5,1.20,1.0,0.00,1.0,1.0,0.0,0.3,1,0,568.0
1048563,1048563,1.0,243.0,41.0,3.20,0.5,3.70,1.0,0.00,1.0,1.0,0.5,0.3,1,0,1538.0
1048564,1048564,2.0,132.0,230.0,13.00,0.5,17.29,2.0,5.76,1.0,2.0,4.5,0.3,1,0,1900.0
1048565,1048565,2.0,41.0,166.0,0.00,0.5,0.99,1.0,0.00,2.0,1.0,0.0,0.3,1,0,400.0
1048566,1048566,1.0,186.0,1.0,16.00,0.0,16.20,1.0,16.50,1.0,3.0,0.0,0.3,1,0,2143.0
1048567,1048567,2.0,236.0,162.0,1.66,0.5,1.12,1.0,0.00,1.0,1.0,1.0,0.3,1,0,343.0
1048568,1048568,2.0,161.0,162.0,0.00,0.5,0.70,1.0,0.00,2.0,1.0,0.5,0.3,1,0,199.0
1048569,1048569,1.0,138.0,230.0,0.00,0.5,10.40,1.0,5.76,2.0,1.0,0.0,0.3,1,0,2762.0
1048570,1048570,1.0,48.0,50.0,1.00,0.5,1.40,1.0,0.00,1.0,1.0,0.5,0.3,1,0,475.0
1048571,1048571,1.0,237.0,166.0,0.00,0.5,3.60,1.0,0.00,2.0,1.0,0.0,0.3,1,0,1397.0
1048572,1048572,1.0,164.0,90.0,2.35,0.5,1.70,1.0,0.00,1.0,1.0,0.5,0.3,1,0,802.0
1048573,1048573,2.0,264.0,264.0,0.00,0.5,1.80,4.0,0.00,2.0,1.0,1.0,0.3,1,0,767.0
1048574,1048574,1.0,74.0,74.0,0.00,0.5,0.30,1.0,0.00,2.0,1.0,0.0,0.3,1,0,166.0

In [301]:
corr=train_copy1.corr()

In [303]:
corr["total+AF8-amount"].sort_values(ascending=False)

total+AF8-amount          1.000000
distance                  0.852937
driver+AF8-tip            0.675221
toll+AF8-amount           0.544115
rate+AF8-code             0.277014
deltas                    0.178911
extra+AF8-charges         0.112625
flag_Y                    0.043338
vendor+AF8-id             0.015648
num+AF8-passengers        0.011966
ID                        0.001859
improvement+AF8-charge   -0.006811
flag_N                   -0.043338
pickup+AF8-loc           -0.069798
drop+AF8-loc             -0.086137
payment+AF8-method       -0.129646
mta+AF8-tax              -0.293919
Name: total+AF8-amount, dtype: float64

In [304]:
from sklearn.model_selection import train_test_split

In [406]:
features2=features.drop(["improvement+AF8-charge","vendor+AF8-id"],axis=1)

In [305]:
x_train,x_test,y_train,y_test=train_test_split(features,target,test_size=0.2,random_state=42)

In [407]:
x2_train,x2_test,y2_train,y2_test=train_test_split(features2,target,test_size=0.2,random_state=42)

In [306]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 838858 entries, 374896 to 121959
Data columns (total 16 columns):
ID                        838858 non-null int64
vendor+AF8-id             838858 non-null float64
pickup+AF8-loc            838858 non-null float64
drop+AF8-loc              838858 non-null float64
driver+AF8-tip            838858 non-null float64
mta+AF8-tax               838858 non-null float64
distance                  838858 non-null float64
num+AF8-passengers        838858 non-null float64
toll+AF8-amount           838858 non-null float64
payment+AF8-method        838858 non-null float64
rate+AF8-code             838858 non-null float64
extra+AF8-charges         838858 non-null float64
improvement+AF8-charge    838858 non-null float64
flag_N                    838858 non-null uint8
flag_Y                    838858 non-null uint8
deltas                    838858 non-null float64
dtypes: float64(13), int64(1), uint8(2)
memory usage: 97.6 MB

In [307]:
from sklearn.linear_model import LinearRegression

In [308]:
lr=LinearRegression()

In [419]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [432]:
lr.fit(x2_train,y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [420]:
y_prediction=lr.predict(x_test)

In [427]:
results=cross_val_score(lr,y_test,y_prediction,scoring="neg_mean_squared_error",cv=2)

In [331]:
from sklearn.model_selection import cross_val_score

In [422]:
y_prediction=y_prediction.reshape(-1,1)

In [423]:
y_prediction

array([[35.37793426],
       [11.04430189],
       [10.00185594],
       ...,
       [27.41031464],
       [ 8.97197963],
       [10.77805969]])

In [424]:
y_test

array([[32.75, 12.96, 11.3 , ..., 28.8 ,  8.3 ,  8.8 ]])

In [425]:
y_test=np.array(y_test,ndmin=2).T

In [426]:
y_test

array([[32.75],
       [12.96],
       [11.3 ],
       ...,
       [28.8 ],
       [ 8.3 ],
       [ 8.8 ]])

In [428]:
res=np.sqrt(-results)

In [429]:
res

array([3.91887541, 4.72537204])

In [335]:
from sklearn.ensemble import RandomForestRegressor

In [336]:
rfr=RandomForestRegressor()

In [337]:
rfr.fit(x_train,y_train)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [338]:
y_pred=rfr.predict(x_test)

In [339]:
result=cross_val_score(rfr,y_test,y_pred,scoring="neg_mean_squared_error",cv=10)

In [340]:
resu=np.sqrt(-result)

In [341]:
resu

array([1.96115064, 3.00026656, 3.13565852, 2.05567517, 2.05007149,
       4.69156559, 2.82591797, 3.06570164, 4.73629678, 2.69187887])

In [342]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154235 entries, 0 to 154234
Data columns (total 16 columns):
ID                    154235 non-null int64
vendor_id             154235 non-null int64
pickup_loc            154235 non-null float64
drop_loc              154235 non-null float64
driver_tip            154235 non-null float64
mta_tax               154235 non-null float64
distance              154235 non-null float64
pickup_time           154235 non-null object
drop_time             154235 non-null object
num_passengers        154235 non-null float64
toll_amount           154235 non-null float64
payment_method        154235 non-null float64
rate_code             154235 non-null float64
stored_flag           154235 non-null object
extra_charges         154235 non-null float64
improvement_charge    154235 non-null float64
dtypes: float64(11), int64(2), object(3)
memory usage: 18.8+ MB

In [343]:
t_t_data=[train,test]

In [348]:
t_t_data=pd.DataFrame(t_t_data)

In [350]:
t_t_data

                                                   0
0                ID  vendor+AF8-id  pickup+AF8-lo...
1              ID  vendor_id  pickup_loc  drop_lo...

In [351]:
test.head(5)

,ID,vendor_id,pickup_loc,drop_loc,driver_tip,mta_tax,distance,pickup_time,drop_time,num_passengers,toll_amount,payment_method,rate_code,stored_flag,extra_charges,improvement_charge
0,0,1,68.0,186.0,1.00,0.5,0.70,04/05/2017 05:49:46 AM,04/05/2017 05:54:03 AM,1.0,0.0,1.0,1.0,N,0.5,0.3
1,1,1,170.0,161.0,2.55,0.5,1.00,04/07/2017 08:57:27 AM,04/07/2017 09:16:00 AM,1.0,0.0,1.0,1.0,N,0.0,0.3
2,2,2,13.0,246.0,2.96,0.5,3.35,04/06/2017 08:06:41 AM,04/06/2017 08:21:33 AM,2.0,0.0,1.0,1.0,N,0.0,0.3
3,3,1,170.0,233.0,2.00,0.5,0.80,04/04/2017 08:31:34 AM,04/04/2017 08:37:21 AM,2.0,0.0,1.0,1.0,N,0.0,0.3
4,4,1,237.0,236.0,1.00,0.5,0.70,04/07/2017 10:54:06 AM,04/07/2017 11:00:59 AM,1.0,0.0,1.0,1.0,Y,0.0,0.3

In [380]:
test_copy1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154235 entries, 0 to 154234
Data columns (total 16 columns):
ID                    154235 non-null int64
vendor_id             154235 non-null int64
pickup_loc            154235 non-null float64
drop_loc              154235 non-null float64
driver_tip            154235 non-null float64
mta_tax               154235 non-null float64
distance              154235 non-null float64
num_passengers        154235 non-null float64
toll_amount           154235 non-null float64
payment_method        154235 non-null float64
rate_code             154235 non-null float64
extra_charges         154235 non-null float64
improvement_charge    154235 non-null float64
flag_N                154235 non-null uint8
flag_Y                154235 non-null uint8
deltas                154235 non-null float64
dtypes: float64(12), int64(2), uint8(2)
memory usage: 16.8 MB

In [434]:
test_copy2=test_copy1.drop(["vendor_id","improvement_charge"],axis=1)

In [433]:
subm=lr.predict(test_copy1)

ValueError: shapes (154235,16) and (14,) not aligned: 16 (dim 1) != 14 (dim 0)

In [435]:
subm=lr.predict(test_copy2)

In [436]:
subm

array([ 8.70790173, 11.6236818 , 18.02499884, ..., 11.28308162,
       14.35960403, 14.03965024])

In [440]:
submission3=pd.DataFrame({'ID':test_copy1["ID"],"total_amount":subm})

In [438]:
submission2

            ID  total_amount
0            0      8.707902
1            1     11.623682
2            2     18.024999
3            3     10.280311
4            4      8.975219
5            5     11.048200
6            6     11.647812
7            7     12.803785
8            8      8.050094
9            9     11.711522
10          10     15.346645
11          11     13.334125
12          12     15.224767
13          13     14.974425
14          14     11.144931
15          15      7.760147
16          16     43.516904
17          17     11.725077
18          18      8.662507
19          19      8.581185
20          20     14.925139
21          21     11.951164
22          22      8.660335
23          23     47.758952
24          24     22.898389
25          25     10.174958
26          26     13.422604
27          27     18.330591
28          28     50.454486
29          29      7.436830
...        ...           ...
154205  154205     42.655864
154206  154206      7.348773
154207  154207     34.578929
154208  154208     12.345135
154209  154209     10.904500
154210  154210     13.650728
154211  154211      9.646752
154212  154212      8.739546
154213  154213     12.341568
154214  154214      8.235383
154215  154215     10.171405
154216  154216     11.800452
154217  154217     11.176926
154218  154218     13.063006
154219  154219     14.432774
154220  154220     17.839217
154221  154221      7.914035
154222  154222      9.101428
154223  154223     14.113039
154224  154224     38.843701
154225  154225     17.517489
154226  154226      7.957361
154227  154227     20.350308
154228  154228     34.716250
154229  154229     10.072860
154230  154230     13.396384
154231  154231      9.527426
154232  154232     11.283082
154233  154233     14.359604
154234  154234     14.039650

[154235 rows x 2 columns]

In [446]:
file3='ola Prediction3.csv'

In [447]:
submission3.to_csv(file3,index=False)

In [448]:
print('file3:'+file3)

file3:ola Prediction3.csv