In [1]:
import pandas as pd

In [2]:
import numpy as np
import random
import math
import time
from sklearn.linear_model import LinearRegression, BayesianRidge
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [3]:
deaths_dir="C:/Users/Asus/Downloads/novel-corona-virus-2019-dataset/time_series_covid_19_deaths.csv"

In [4]:
recoveries_dir="C:/Users/Asus/Downloads/novel-corona-virus-2019-dataset/time_series_covid_19_recovered.csv"

In [5]:
confirmed_dir="C:/Users/Asus/Downloads/novel-corona-virus-2019-dataset/time_series_covid_19_confirmed.csv"

In [6]:
deaths=pd.read_csv(deaths_dir)

In [7]:
recovered=pd.read_csv(recoveries_dir)

In [8]:
confirmed=pd.read_csv(confirmed_dir)

In [9]:
deaths

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20
0,NaN,Thailand,15.0000,101.0000,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
1,NaN,Japan,36.0000,138.0000,0,0,0,0,0,0,...,15,16,19,22,22,27,29,29,29,33
2,NaN,Singapore,1.2833,103.8333,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,Nepal,28.1667,84.2500,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,Malaysia,2.5000,112.5000,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,2,3
5,British Columbia,Canada,49.2827,-123.1207,0,0,0,0,0,0,...,1,1,1,1,1,4,4,7,7,8
6,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,0,0,...,2,2,2,2,2,2,4,5,5,6
7,Victoria,Australia,-37.8136,144.9631,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Queensland,Australia,-28.0167,153.4000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,NaN,Cambodia,11.5500,104.9167,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,NaN,Sri Lanka,7.0000,81.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,NaN,Germany,51.0000,9.0000,0,0,0,0,0,0,...,3,3,7,9,11,17,24,28,44,67
12,NaN,Finland,64.0000,26.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,NaN,United Arab Emirates,24.0000,54.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
14,NaN,Philippines,13.0000,122.0000,0,0,0,0,0,0,...,1,2,5,8,11,12,12,19,17,18
15,NaN,India,21.0000,78.0000,0,0,0,0,0,0,...,1,1,2,2,2,2,3,3,4,5
16,NaN,Italy,43.0000,12.0000,0,0,0,0,0,0,...,827,827,1266,1441,1809,2158,2503,2978,3405,4032
17,NaN,Sweden,63.0000,16.0000,0,0,0,0,0,0,...,1,1,1,2,3,6,7,10,11,16
18,NaN,Spain,40.0000,-4.0000,0,0,0,0,0,0,...,54,55,133,195,289,342,533,623,830,1043
19,South Australia,Australia,-34.9285,138.6007,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,NaN,Belgium,50.8333,4.0000,0,0,0,0,0,0,...,3,3,3,4,4,5,10,14,21,37
21,NaN,Egypt,26.0000,30.0000,0,0,0,0,0,0,...,1,1,2,2,2,2,4,6,6,8
22,From Diamond Princess,Australia,35.4437,139.6380,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,NaN,Lebanon,33.8547,35.8623,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,4,4
24,NaN,Iraq,33.0000,44.0000,0,0,0,0,0,0,...,7,8,9,10,10,10,11,12,13,17
25,NaN,Oman,21.0000,57.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,NaN,Bahrain,26.0275,50.5500,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
28,NaN,Kuwait,29.5000,47.7500,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,0,1,2,3,4,4,4,7,9,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,NaN,Tanzania,-6.3690,34.8888,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
448,Virgin Islands,US,18.3358,-64.8963,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
449,Cayman Islands,United Kingdom,19.3133,-81.2546,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
450,Reunion,France,-21.1351,55.2471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
451,NaN,Barbados,13.1939,-59.5432,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
452,NaN,Montenegro,42.5000,19.3000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
453,NaN,Kyrgyzstan,41.2044,74.7661,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
454,NaN,Mauritius,-20.2000,57.5000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
455,Aruba,Netherlands,12.5186,-70.0358,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
456,NaN,Zambia,-15.4167,28.2833,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
457,NaN,Djibouti,11.8251,42.5903,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
458,NaN,"Gambia, The",13.4432,-15.3101,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
459,Montserrat,United Kingdom,16.7425,-62.1874,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
460,NaN,"Bahamas, The",25.0343,-77.3963,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
461,Greenland,Denmark,71.7069,-42.6043,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
462,New Caledonia,France,-20.9043,165.6180,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
463,Bermuda,United Kingdom,32.3078,-64.7505,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
464,NaN,Chad,15.4542,18.7322,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
465,NaN,El Salvador,13.7942,-88.8965,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
466,NaN,Fiji,-17.7134,178.0650,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
467,NaN,Nicaragua,12.8654,-85.2072,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
468,NaN,Madagascar,-18.7669,46.8691,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
469,NaN,Haiti,18.9712,-72.2852,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
470,NaN,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
471,NaN,Cabo Verde,16.5388,-23.0418,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
472,Sint Maarten,Netherlands,18.0425,-63.0548,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
473,NaN,Niger,17.6078,8.0817,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
474,NaN,Papua New Guinea,-6.3150,143.9555,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
475,Isle of Man,United Kingdom,54.2361,-4.5481,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
476,NaN,Zimbabwe,-20.0000,30.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
m=-1
for i in deaths["Province/State"]:
    m=m+1
    if(pd.isna(i)==True):
        deaths.iloc[m,0]=deaths.iloc[m,1]

In [13]:
deaths

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20
0,Thailand,Thailand,15.0000,101.0000,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
1,Japan,Japan,36.0000,138.0000,0,0,0,0,0,0,...,15,16,19,22,22,27,29,29,29,33
2,Singapore,Singapore,1.2833,103.8333,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Nepal,Nepal,28.1667,84.2500,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Malaysia,Malaysia,2.5000,112.5000,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,2,3
5,British Columbia,Canada,49.2827,-123.1207,0,0,0,0,0,0,...,1,1,1,1,1,4,4,7,7,8
6,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,0,0,...,2,2,2,2,2,2,4,5,5,6
7,Victoria,Australia,-37.8136,144.9631,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Queensland,Australia,-28.0167,153.4000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Cambodia,Cambodia,11.5500,104.9167,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Sri Lanka,Sri Lanka,7.0000,81.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Germany,Germany,51.0000,9.0000,0,0,0,0,0,0,...,3,3,7,9,11,17,24,28,44,67
12,Finland,Finland,64.0000,26.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,United Arab Emirates,United Arab Emirates,24.0000,54.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
14,Philippines,Philippines,13.0000,122.0000,0,0,0,0,0,0,...,1,2,5,8,11,12,12,19,17,18
15,India,India,21.0000,78.0000,0,0,0,0,0,0,...,1,1,2,2,2,2,3,3,4,5
16,Italy,Italy,43.0000,12.0000,0,0,0,0,0,0,...,827,827,1266,1441,1809,2158,2503,2978,3405,4032
17,Sweden,Sweden,63.0000,16.0000,0,0,0,0,0,0,...,1,1,1,2,3,6,7,10,11,16
18,Spain,Spain,40.0000,-4.0000,0,0,0,0,0,0,...,54,55,133,195,289,342,533,623,830,1043
19,South Australia,Australia,-34.9285,138.6007,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,Belgium,Belgium,50.8333,4.0000,0,0,0,0,0,0,...,3,3,3,4,4,5,10,14,21,37
21,Egypt,Egypt,26.0000,30.0000,0,0,0,0,0,0,...,1,1,2,2,2,2,4,6,6,8
22,From Diamond Princess,Australia,35.4437,139.6380,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Lebanon,Lebanon,33.8547,35.8623,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,4,4
24,Iraq,Iraq,33.0000,44.0000,0,0,0,0,0,0,...,7,8,9,10,10,10,11,12,13,17
25,Oman,Oman,21.0000,57.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,Afghanistan,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,Bahrain,Bahrain,26.0275,50.5500,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
28,Kuwait,Kuwait,29.5000,47.7500,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Algeria,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,0,1,2,3,4,4,4,7,9,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Tanzania,Tanzania,-6.3690,34.8888,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
448,Virgin Islands,US,18.3358,-64.8963,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
449,Cayman Islands,United Kingdom,19.3133,-81.2546,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
450,Reunion,France,-21.1351,55.2471,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
451,Barbados,Barbados,13.1939,-59.5432,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
452,Montenegro,Montenegro,42.5000,19.3000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
453,Kyrgyzstan,Kyrgyzstan,41.2044,74.7661,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
454,Mauritius,Mauritius,-20.2000,57.5000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
455,Aruba,Netherlands,12.5186,-70.0358,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
456,Zambia,Zambia,-15.4167,28.2833,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
457,Djibouti,Djibouti,11.8251,42.5903,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
458,"Gambia, The","Gambia, The",13.4432,-15.3101,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
459,Montserrat,United Kingdom,16.7425,-62.1874,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
460,"Bahamas, The","Bahamas, The",25.0343,-77.3963,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
461,Greenland,Denmark,71.7069,-42.6043,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
462,New Caledonia,France,-20.9043,165.6180,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
463,Bermuda,United Kingdom,32.3078,-64.7505,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
464,Chad,Chad,15.4542,18.7322,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
465,El Salvador,El Salvador,13.7942,-88.8965,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
466,Fiji,Fiji,-17.7134,178.0650,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
467,Nicaragua,Nicaragua,12.8654,-85.2072,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
468,Madagascar,Madagascar,-18.7669,46.8691,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
469,Haiti,Haiti,18.9712,-72.2852,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
470,Angola,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
471,Cabo Verde,Cabo Verde,16.5388,-23.0418,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
472,Sint Maarten,Netherlands,18.0425,-63.0548,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
473,Niger,Niger,17.6078,8.0817,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
474,Papua New Guinea,Papua New Guinea,-6.3150,143.9555,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
475,Isle of Man,United Kingdom,54.2361,-4.5481,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
476,Zimbabwe,Zimbabwe,-20.0000,30.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
m=-1
for i in confirmed["Province/State"]:
    m=m+1
    if(pd.isna(i)==True):
        confirmed.iloc[m,0]=confirmed.iloc[m,1]

In [15]:
m=-1
for i in recovered["Province/State"]:
    m=m+1
    if(pd.isna(i)==True):
        recovered.iloc[m,0]=recovered.iloc[m,1]

In [16]:
confirmed

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20
0,Thailand,Thailand,15.0000,101.0000,2,3,5,7,8,8,...,59,70,75,82,114,147,177,212,272,322
1,Japan,Japan,36.0000,138.0000,2,1,2,2,4,4,...,639,639,701,773,839,825,878,889,924,963
2,Singapore,Singapore,1.2833,103.8333,0,1,3,3,4,5,...,178,178,200,212,226,243,266,313,345,385
3,Nepal,Nepal,28.1667,84.2500,0,0,0,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,Malaysia,Malaysia,2.5000,112.5000,0,0,0,3,4,4,...,149,149,197,238,428,566,673,790,900,1030
5,British Columbia,Canada,49.2827,-123.1207,0,0,0,0,0,0,...,39,46,64,64,73,103,103,186,231,271
6,New South Wales,Australia,-33.8688,151.2093,0,0,0,0,3,4,...,65,65,92,112,134,171,210,267,307,353
7,Victoria,Australia,-37.8136,144.9631,0,0,0,0,1,1,...,21,21,36,49,57,71,94,121,121,121
8,Queensland,Australia,-28.0167,153.4000,0,0,0,0,0,0,...,20,20,35,46,61,68,78,94,144,184
9,Cambodia,Cambodia,11.5500,104.9167,0,0,0,0,0,1,...,3,3,5,7,7,7,33,35,37,51
10,Sri Lanka,Sri Lanka,7.0000,81.0000,0,0,0,0,0,1,...,2,2,6,10,18,28,44,51,60,73
11,Germany,Germany,51.0000,9.0000,0,0,0,0,0,1,...,1908,2078,3675,4585,5795,7272,9257,12327,15320,19848
12,Finland,Finland,64.0000,26.0000,0,0,0,0,0,0,...,59,59,155,225,244,277,321,336,400,450
13,United Arab Emirates,United Arab Emirates,24.0000,54.0000,0,0,0,0,0,0,...,74,85,85,85,98,98,98,113,140,140
14,Philippines,Philippines,13.0000,122.0000,0,0,0,0,0,0,...,49,52,64,111,140,142,187,202,217,230
15,India,India,21.0000,78.0000,0,0,0,0,0,0,...,62,73,82,102,113,119,142,156,194,244
16,Italy,Italy,43.0000,12.0000,0,0,0,0,0,0,...,12462,12462,17660,21157,24747,27980,31506,35713,41035,47021
17,Sweden,Sweden,63.0000,16.0000,0,0,0,0,0,0,...,500,599,814,961,1022,1103,1190,1279,1439,1639
18,Spain,Spain,40.0000,-4.0000,0,0,0,0,0,0,...,2277,2277,5232,6391,7798,9942,11748,13910,17963,20410
19,South Australia,Australia,-34.9285,138.6007,0,0,0,0,0,0,...,9,9,16,19,20,29,29,37,42,50
20,Belgium,Belgium,50.8333,4.0000,0,0,0,0,0,0,...,314,314,559,689,886,1058,1243,1486,1795,2257
21,Egypt,Egypt,26.0000,30.0000,0,0,0,0,0,0,...,60,67,80,109,110,150,196,196,256,285
22,From Diamond Princess,Australia,35.4437,139.6380,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Lebanon,Lebanon,33.8547,35.8623,0,0,0,0,0,0,...,61,61,77,93,110,99,120,133,157,163
24,Iraq,Iraq,33.0000,44.0000,0,0,0,0,0,0,...,71,71,101,110,116,124,154,164,192,208
25,Oman,Oman,21.0000,57.0000,0,0,0,0,0,0,...,18,18,19,19,22,22,24,39,48,48
26,Afghanistan,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,7,7,7,11,16,21,22,22,22,24
27,Bahrain,Bahrain,26.0275,50.5500,0,0,0,0,0,0,...,195,195,189,210,214,214,228,256,278,285
28,Kuwait,Kuwait,29.5000,47.7500,0,0,0,0,0,0,...,72,80,80,104,112,123,130,142,148,159
29,Algeria,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,20,24,26,37,48,54,60,74,87,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Tanzania,Tanzania,-6.3690,34.8888,0,0,0,0,0,0,...,0,0,0,0,0,1,1,3,6,6
448,Virgin Islands,US,18.3358,-64.8963,0,0,0,0,0,0,...,0,0,0,1,1,1,2,2,3,3
449,Cayman Islands,United Kingdom,19.3133,-81.2546,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,3,3
450,Reunion,France,-21.1351,55.2471,0,0,0,0,0,0,...,1,1,5,6,7,9,9,12,14,28
451,Barbados,Barbados,13.1939,-59.5432,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,5,5
452,Montenegro,Montenegro,42.5000,19.3000,0,0,0,0,0,0,...,0,0,0,0,0,0,2,1,3,14
453,Kyrgyzstan,Kyrgyzstan,41.2044,74.7661,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,3,6
454,Mauritius,Mauritius,-20.2000,57.5000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,3,12
455,Aruba,Netherlands,12.5186,-70.0358,0,0,0,0,0,0,...,0,0,2,2,2,2,3,4,4,5
456,Zambia,Zambia,-15.4167,28.2833,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,2
457,Djibouti,Djibouti,11.8251,42.5903,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
458,"Gambia, The","Gambia, The",13.4432,-15.3101,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
459,Montserrat,United Kingdom,16.7425,-62.1874,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
460,"Bahamas, The","Bahamas, The",25.0343,-77.3963,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,3,3
461,Greenland,Denmark,71.7069,-42.6043,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,2,2
462,New Caledonia,France,-20.9043,165.6180,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,2
463,Bermuda,United Kingdom,32.3078,-64.7505,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,2
464,Chad,Chad,15.4542,18.7322,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
465,El Salvador,El Salvador,13.7942,-88.8965,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
466,Fiji,Fiji,-17.7134,178.0650,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
467,Nicaragua,Nicaragua,12.8654,-85.2072,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
468,Madagascar,Madagascar,-18.7669,46.8691,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
469,Haiti,Haiti,18.9712,-72.2852,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
470,Angola,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
471,Cabo Verde,Cabo Verde,16.5388,-23.0418,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
472,Sint Maarten,Netherlands,18.0425,-63.0548,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
473,Niger,Niger,17.6078,8.0817,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
474,Papua New Guinea,Papua New Guinea,-6.3150,143.9555,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
475,Isle of Man,United Kingdom,54.2361,-4.5481,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
476,Zimbabwe,Zimbabwe,-20.0000,30.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [17]:
deaths.drop(['Country/Region'],axis=1,inplace=True)

In [18]:
confirmed.drop(['Country/Region'],axis=1,inplace=True)

In [19]:
recovered.drop(['Country/Region'],axis=1,inplace=True)

In [20]:
deaths.rename(columns={'Province/State':'Province/State/Country'},inplace=True)

In [21]:
deaths

,Province/State/Country,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,...,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20
0,Thailand,15.0000,101.0000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
1,Japan,36.0000,138.0000,0,0,0,0,0,0,0,...,15,16,19,22,22,27,29,29,29,33
2,Singapore,1.2833,103.8333,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Nepal,28.1667,84.2500,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Malaysia,2.5000,112.5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,2,2,3
5,British Columbia,49.2827,-123.1207,0,0,0,0,0,0,0,...,1,1,1,1,1,4,4,7,7,8
6,New South Wales,-33.8688,151.2093,0,0,0,0,0,0,0,...,2,2,2,2,2,2,4,5,5,6
7,Victoria,-37.8136,144.9631,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Queensland,-28.0167,153.4000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Cambodia,11.5500,104.9167,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Sri Lanka,7.0000,81.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Germany,51.0000,9.0000,0,0,0,0,0,0,0,...,3,3,7,9,11,17,24,28,44,67
12,Finland,64.0000,26.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,United Arab Emirates,24.0000,54.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
14,Philippines,13.0000,122.0000,0,0,0,0,0,0,0,...,1,2,5,8,11,12,12,19,17,18
15,India,21.0000,78.0000,0,0,0,0,0,0,0,...,1,1,2,2,2,2,3,3,4,5
16,Italy,43.0000,12.0000,0,0,0,0,0,0,0,...,827,827,1266,1441,1809,2158,2503,2978,3405,4032
17,Sweden,63.0000,16.0000,0,0,0,0,0,0,0,...,1,1,1,2,3,6,7,10,11,16
18,Spain,40.0000,-4.0000,0,0,0,0,0,0,0,...,54,55,133,195,289,342,533,623,830,1043
19,South Australia,-34.9285,138.6007,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,Belgium,50.8333,4.0000,0,0,0,0,0,0,0,...,3,3,3,4,4,5,10,14,21,37
21,Egypt,26.0000,30.0000,0,0,0,0,0,0,0,...,1,1,2,2,2,2,4,6,6,8
22,From Diamond Princess,35.4437,139.6380,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Lebanon,33.8547,35.8623,0,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,4,4
24,Iraq,33.0000,44.0000,0,0,0,0,0,0,0,...,7,8,9,10,10,10,11,12,13,17
25,Oman,21.0000,57.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,Bahrain,26.0275,50.5500,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
28,Kuwait,29.5000,47.7500,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Algeria,28.0339,1.6596,0,0,0,0,0,0,0,...,0,1,2,3,4,4,4,7,9,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Tanzania,-6.3690,34.8888,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
448,Virgin Islands,18.3358,-64.8963,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
449,Cayman Islands,19.3133,-81.2546,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
450,Reunion,-21.1351,55.2471,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
451,Barbados,13.1939,-59.5432,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
452,Montenegro,42.5000,19.3000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
453,Kyrgyzstan,41.2044,74.7661,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
454,Mauritius,-20.2000,57.5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
455,Aruba,12.5186,-70.0358,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
456,Zambia,-15.4167,28.2833,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
457,Djibouti,11.8251,42.5903,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
458,"Gambia, The",13.4432,-15.3101,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
459,Montserrat,16.7425,-62.1874,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
460,"Bahamas, The",25.0343,-77.3963,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
461,Greenland,71.7069,-42.6043,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
462,New Caledonia,-20.9043,165.6180,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
463,Bermuda,32.3078,-64.7505,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
464,Chad,15.4542,18.7322,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
465,El Salvador,13.7942,-88.8965,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
466,Fiji,-17.7134,178.0650,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
467,Nicaragua,12.8654,-85.2072,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
468,Madagascar,-18.7669,46.8691,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
469,Haiti,18.9712,-72.2852,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
470,Angola,-11.2027,17.8739,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
471,Cabo Verde,16.5388,-23.0418,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
472,Sint Maarten,18.0425,-63.0548,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
473,Niger,17.6078,8.0817,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
474,Papua New Guinea,-6.3150,143.9555,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
475,Isle of Man,54.2361,-4.5481,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
476,Zimbabwe,-20.0000,30.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
recovered.rename(columns={'Province/State':'Province/State/Country'},inplace=True)
confirmed.rename(columns={'Province/State':'Province/State/Country'},inplace=True)

In [239]:
recovered

,Province/State/Country,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,...,03-11-2020,03-12-2020,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20
0,Thailand,15.0000,101.0000,0,0,0,0,2,2,5,...,34,34,35,35,35,35,41,42,42,42
1,Japan,36.0000,138.0000,0,0,0,0,1,1,1,...,118,118,118,118,118,144,144,144,150,191
2,Singapore,1.2833,103.8333,0,0,0,0,0,0,0,...,96,96,97,105,105,109,114,114,114,124
3,Nepal,28.1667,84.2500,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
4,Malaysia,2.5000,112.5000,0,0,0,0,0,0,0,...,26,26,26,35,42,42,49,60,75,87
5,British Columbia,49.2827,-123.1207,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
6,New South Wales,-33.8688,151.2093,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
7,Victoria,-37.8136,144.9631,0,0,0,0,0,0,0,...,7,7,8,8,8,8,8,8,8,8
8,Queensland,-28.0167,153.4000,0,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
9,Cambodia,11.5500,104.9167,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
10,Sri Lanka,7.0000,81.0000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,3,3
11,Germany,51.0000,9.0000,0,0,0,0,0,0,0,...,25,25,46,46,46,67,67,105,113,180
12,Finland,64.0000,26.0000,0,0,0,0,0,0,0,...,1,1,1,1,10,10,10,10,10,10
13,United Arab Emirates,24.0000,54.0000,0,0,0,0,0,0,0,...,17,17,17,17,23,23,23,26,31,31
14,Philippines,13.0000,122.0000,0,0,0,0,0,0,0,...,2,2,2,2,2,2,5,5,8,8
15,India,21.0000,78.0000,0,0,0,0,0,0,0,...,4,4,4,4,13,13,14,14,15,20
16,Italy,43.0000,12.0000,0,0,0,0,0,0,0,...,1045,1045,1439,1966,2335,2749,2941,4025,4440,4440
17,Sweden,63.0000,16.0000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,16,16
18,Spain,40.0000,-4.0000,0,0,0,0,0,0,0,...,183,183,193,517,517,530,1028,1081,1107,1588
19,South Australia,-34.9285,138.6007,0,0,0,0,0,0,0,...,2,2,3,3,3,3,3,3,3,3
20,Belgium,50.8333,4.0000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,31,31,1
21,Egypt,26.0000,30.0000,0,0,0,0,0,0,0,...,27,27,27,27,21,27,32,32,32,39
22,From Diamond Princess,35.4437,139.6380,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Lebanon,33.8547,35.8623,0,0,0,0,0,0,0,...,1,1,1,1,1,1,3,3,4,4
24,Iraq,33.0000,44.0000,0,0,0,0,0,0,0,...,15,15,24,26,26,26,32,43,43,49
25,Oman,21.0000,57.0000,0,0,0,0,0,0,0,...,9,9,9,9,9,9,9,12,12,12
26,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,1,1
27,Bahrain,26.0275,50.5500,0,0,0,0,0,0,0,...,35,35,44,44,60,77,81,88,100,100
28,Kuwait,29.5000,47.7500,0,0,0,0,0,0,0,...,2,5,5,5,5,9,9,15,18,18
29,Algeria,28.0339,1.6596,0,0,0,0,0,0,0,...,0,8,8,12,12,12,12,12,32,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,Tanzania,-6.3690,34.8888,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
448,Virgin Islands,18.3358,-64.8963,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
449,Cayman Islands,19.3133,-81.2546,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
450,Reunion,-21.1351,55.2471,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
451,Barbados,13.1939,-59.5432,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
452,Montenegro,42.5000,19.3000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
453,Kyrgyzstan,41.2044,74.7661,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
454,Mauritius,-20.2000,57.5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
455,Aruba,12.5186,-70.0358,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
456,Zambia,-15.4167,28.2833,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
457,Djibouti,11.8251,42.5903,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
458,"Gambia, The",13.4432,-15.3101,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
459,Montserrat,16.7425,-62.1874,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
460,"Bahamas, The",25.0343,-77.3963,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
461,Greenland,71.7069,-42.6043,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
462,New Caledonia,-20.9043,165.6180,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
463,Bermuda,32.3078,-64.7505,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
464,Chad,15.4542,18.7322,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
465,El Salvador,13.7942,-88.8965,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
466,Fiji,-17.7134,178.0650,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
467,Nicaragua,12.8654,-85.2072,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
468,Madagascar,-18.7669,46.8691,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
469,Haiti,18.9712,-72.2852,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
470,Angola,-11.2027,17.8739,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
471,Cabo Verde,16.5388,-23.0418,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
472,Sint Maarten,18.0425,-63.0548,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
473,Niger,17.6078,8.0817,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
474,Papua New Guinea,-6.3150,143.9555,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
475,Isle of Man,54.2361,-4.5481,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
476,Zimbabwe,-20.0000,30.0000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
columns=deaths.keys()
columns2=recovered.keys()

In [25]:
dead = deaths.loc[:, columns[3]:columns[-1]]
confirm=confirmed.loc[:,columns[3]:columns[-1]]
recoveries = recovered.loc[:, columns2[3]:columns2[-1]]

In [57]:
from sklearn.linear_model import LogisticRegression as lor

In [74]:
die=np.array(confirm.loc[0,dates[0]:dates[-1]]).reshape(-1,1)
X_train_confirmed, X_test_confirmed, y_train_confirmed, y_test_confirmed = train_test_split(days_since_1_22, die,test_size=0.15,shuffle=False)
lor_model = lor(penalty='none', solver='lbfgs',fit_intercept=False)
lor_model.fit(X_train_confirmed, y_train_confirmed)
test_lor_pred = lor_model.predict(X_test_confirmed)
predlor= lor_model.predict(future_forcast)
prearrlor=np.asarray(pred)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [75]:
prearrlor=prearrlor.T

In [76]:
prearrlor

array([ 2, 14, 14, 19, 19, 19, 19, 19, 19, 35, 35, 35, 35, 35, 35, 35, 35,
       35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
       35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
       35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
       35, 35, 35, 35, 35, 35], dtype=int64)

In [36]:
dates=dead.keys()
dates2=recoveries.keys()

In [37]:
days_in_future = 15
future_forcast = np.array([i for i in range(len(dates)+days_in_future)]).reshape(-1, 1)
adjusted_dates = future_forcast[:-15]

In [49]:
days_since_1_22 = np.array([i for i in range(len(dates))]).reshape(-1, 1)

In [79]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

In [157]:
poly_features=PolynomialFeatures(degree=7,include_bias=False)
lr=LinearRegression(normalize=False)

In [166]:
poly=poly_features.fit_transform(X_train_confirmed)

In [167]:
lr.fit(poly,y_train_confirmed)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [168]:
poly_test=poly_features.fit_transform(X_test_confirmed)
poly_total=poly_features.fit_transform(future_forcast)

In [169]:
test_linear_pred = lr.predict(poly_test)
pred= lr.predict(poly_total)
prearr=np.asarray(pred)

In [240]:
die=np.array(confirm.loc[1,dates[0]:dates[-1]]).reshape(-1,1)
X_train_confirmed, X_test_confirmed, y_train_confirmed, y_test_confirmed = train_test_split(days_since_1_22, die, test_size=0.15, shuffle=False)
poly=poly_features.fit_transform(X_train_confirmed)
lr.fit(poly,y_train_confirmed)
poly_test=poly_features.fit_transform(X_test_confirmed)
poly_total=poly_features.fit_transform(future_forcast)
test_linear_pred = lr.predict(poly_test)
pred= lr.predict(poly_total)
linarr=np.asarray(pred)
linarr=linarr.T

In [233]:

for i in range(1,477):
    died=np.array(confirm.loc[i,dates[0]:dates[-1]]).reshape(-1,1)
    X_train_confirmed, X_test_confirmed, y_train_confirmed, y_test_confirmed = train_test_split(days_since_1_22, died, test_size=0.15, shuffle=False)
    poly=poly_features.fit_transform(X_train_confirmed)
    lr.fit(poly,y_train_confirmed)
    poly_test=poly_features.fit_transform(X_test_confirmed)
    poly_total=poly_features.fit_transform(future_forcast)
    test_linear_pred = lr.predict(poly_test)
    pred= lr.predict(poly_total)
    prearr=np.asarray(pred)
    prearr=prearr.T
    linarr=np.concatenate((linarr,prearr))

In [234]:
linarr

array([[ 1.14081301e+00,  3.59199214e+00,  5.50162193e+00, ...,
         3.16023031e+03,  3.73822585e+03,  4.40412888e+03],
       [ 8.53991367e+00, -6.76608452e-01, -3.92487948e+00, ...,
        -1.62004563e+03, -2.55137452e+03, -3.68113717e+03],
       [ 4.60426447e-02,  8.88257558e-01,  2.00008751e+00, ...,
        -5.34865366e+03, -6.46898181e+03, -7.76575394e+03],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [241]:
die

array([[  2],
       [  1],
       [  2],
       [  2],
       [  4],
       [  4],
       [  7],
       [  7],
       [ 11],
       [ 15],
       [ 20],
       [ 20],
       [ 20],
       [ 22],
       [ 22],
       [ 45],
       [ 25],
       [ 25],
       [ 26],
       [ 26],
       [ 26],
       [ 28],
       [ 28],
       [ 29],
       [ 43],
       [ 59],
       [ 66],
       [ 74],
       [ 84],
       [ 94],
       [105],
       [122],
       [147],
       [159],
       [170],
       [189],
       [214],
       [228],
       [241],
       [256],
       [274],
       [293],
       [331],
       [360],
       [420],
       [461],
       [502],
       [511],
       [581],
       [639],
       [639],
       [701],
       [773],
       [839],
       [825],
       [878],
       [889],
       [924],
       [963]], dtype=int64)

In [236]:
df = pd.DataFrame(linarr)

In [237]:
df

,0,1,2,3,4,5,6,7,8,9,...,64,65,66,67,68,69,70,71,72,73
0,1.140813,3.591992,5.501622,7.103044,8.564601,10.000855,11.482666,13.046178,14.700776,16.436049,...,861.677052,1051.848678,1278.099800,1545.795009,1860.896630,2230.011620,2660.440777,3160.230312,3738.225846,4404.128877
1,8.539914,-0.676608,-3.924879,-3.219589,-0.132042,4.146803,8.748761,13.076078,16.754116,19.588830,...,1229.286929,1089.899057,886.148299,604.968990,231.543003,-250.857478,-861.035818,-1620.045627,-2551.374520,-3681.137169
2,0.046043,0.888258,2.000088,3.246667,4.554626,5.897623,7.283663,8.744111,10.324293,12.075601,...,-1009.286494,-1352.944034,-1768.455191,-2266.710400,-2859.792925,-3561.069065,-4385.282615,-5348.653660,-6468.981808,-7765.753942
3,-0.206085,0.180620,0.468858,0.678303,0.825628,0.924834,0.987560,1.023368,1.040006,1.043646,...,3.159157,3.892685,4.814689,5.961444,7.374314,9.100245,11.192290,13.710163,16.720822,20.299085
4,0.610106,-0.088751,0.365733,1.459566,2.828265,4.228708,5.514117,6.612036,7.505124,8.214619,...,-1838.832171,-2406.675003,-3091.919733,-3912.234781,-4887.221557,-6038.561619,-7390.170847,-8968.360800,-10802.007406,-12922.727154
5,0.401768,-0.130520,-0.299899,-0.237528,-0.040721,0.221171,0.501488,0.771589,1.016726,1.232462,...,-166.562511,-243.657818,-338.813246,-454.932801,-595.252516,-763.366587,-963.254796,-1199.311235,-1476.374384,-1799.758551
6,-0.414959,-0.020003,0.646849,1.423403,2.195471,2.888106,3.457771,3.885410,4.170364,4.325102,...,-176.481059,-285.339808,-421.159602,-588.359848,-791.869004,-1037.164741,-1330.316082,-1678.027549,-2087.685374,-2567.405811
7,-0.175408,-0.039428,0.135358,0.361748,0.642856,0.974495,1.347264,1.748360,2.163118,2.576301,...,455.611292,548.159889,656.561087,782.973591,929.778501,1099.595536,1295.300013,1520.040580,1777.257737,2070.703146
8,-0.235914,-0.022374,0.094206,0.179949,0.280685,0.425489,0.629871,0.898625,1.228367,1.609765,...,207.778756,251.844873,304.535665,367.206985,441.373938,528.723910,631.130272,750.666751,889.622501,1050.517888
9,-0.124120,-0.030217,0.105511,0.261973,0.423127,0.577244,0.716236,0.835041,0.931069,1.003700,...,31.580846,34.777934,37.980671,41.120450,44.114974,46.866800,49.261804,51.167544,52.431544,52.879473
10,-0.162344,-0.020225,0.134345,0.291354,0.443071,0.583768,0.709451,0.817614,0.907011,0.977435,...,38.871408,45.826060,53.746546,62.729296,72.876967,84.298633,97.109963,111.433406,127.398363,145.141358
11,6.067218,-2.587197,-5.319328,-4.458548,-1.721013,1.684822,4.963296,7.646810,9.520789,10.557917,...,13808.713902,14949.426579,16076.434567,17168.268933,18199.839912,19142.097142,19961.671519,20620.498200,21075.420314,21277.772931
12,-0.558808,0.113725,0.388593,0.436726,0.379986,0.300429,0.248493,0.250184,0.313314,0.432845,...,1927.845606,2310.625038,2755.955247,3271.982130,3867.662620,4552.822613,5338.217553,6235.595705,7257.764198,8418.657880
13,-0.201785,-0.156262,-0.029027,0.198081,0.528340,0.954036,1.459844,2.025709,2.629262,3.247813,...,1390.164171,1646.565978,1943.092159,2284.795668,2677.217223,3126.419070,3639.020229,4222.233267,4883.902625,5632.544520
14,-0.575520,0.216700,0.447355,0.382533,0.209455,0.051538,-0.018278,0.034145,0.214272,0.507556,...,2776.713806,3355.659679,4032.078585,4818.896199,5730.339482,6782.030271,7991.083159,9376.207753,10957.815412,12758.130560
15,0.824493,-0.342295,-0.755974,-0.695618,-0.367584,0.081530,0.553342,0.987491,1.352714,1.639126,...,-942.278752,-1216.430390,-1545.642818,-1938.044714,-2402.643053,-2949.389493,-3589.249935,-4334.277296,-5197.687597,-6193.939417
16,8.813701,-2.299782,-6.475802,-6.482267,-4.321424,-1.372063,1.483424,3.746593,5.204559,5.845108,...,95385.901656,106174.968684,117856.026401,130471.242380,144062.129386,158669.266394,174331.999639,191088.123123,208973.538059,228021.890682
17,-1.287348,0.454906,1.009297,0.903210,0.506397,0.062685,-0.282311,-0.457196,-0.444308,-0.262488,...,12372.101142,14632.856463,17234.842197,20219.421052,23631.823182,27521.407891,31941.936750,36951.858352,42614.604954,48998.901249
18,-24.542607,8.637860,19.956888,18.431160,10.583994,0.905604,-7.739008,-13.751705,-16.489566,-15.997125,...,91198.730117,109547.857004,130914.896592,155694.209879,184319.509353,217266.675623,255056.702890,298258.776091,347493.482537,403436.160891
19,0.296643,-0.085072,-0.263888,-0.292503,-0.213589,-0.061254,0.137648,0.362340,0.597081,0.830246,...,-130.537674,-164.519461,-204.792835,-252.233611,-307.808482,-372.581731,-447.722261,-534.510945,-634.348314,-748.762579
20,7.184572,-2.231136,-5.679101,-5.507894,-3.450951,-0.732621,1.836804,3.776561,4.860855,5.053745,...,-4775.024227,-6319.278883,-8196.939198,-10460.067482,-13166.613949,-16380.878845,-20173.997269,-24624.447187,-29818.581184,-35851.182473
21,1.918373,-0.554623,-1.484321,-1.467895,-0.949534,-0.246106,0.429754,0.949036,1.248090,1.312598,...,-786.726446,-1076.660572,-1433.270614,-1867.407628,-2391.187703,-3018.093627,-3763.081630,-4642.693337,-5675.173040,-6880.590419
22,0.931232,-0.206032,-0.687402,-0.740280,-0.541768,-0.225668,0.111094,0.402572,0.608440,0.709120,...,205.223507,234.608424,265.612320,297.906320,331.068307,364.571780,397.773982,429.903312,460.045974,487.131858
23,-0.815307,0.237798,0.631637,0.622945,0.401817,0.103174,-0.182987,-0.402477,-0.528900,-0.556653,...,1549.264835,1862.464207,2228.810828,2655.542080,3150.649043,3722.932666,4382.062601,5138.638760,6004.255662,6991.569624
24,-0.295222,0.041362,0.206552,0.246347,0.201839,0.108556,-0.003951,-0.112285,-0.199180,-0.253284,...,-732.565997,-926.449267,-1154.494963,-1421.077383,-1730.978506,-2089.414462,-2502.063075,-2975.092504,-3515.191002,-4129.597819
25,-0.230168,0.053649,0.171320,0.181309,0.129152,0.049158,-0.034002,-0.103811,-0.150525,-0.169904,...,-275.637104,-333.702071,-400.110625,-475.701638,-561.369611,-658.066656,-766.804495,-888.656445,-1024.759422,-1176.315929
26,-0.019827,0.023769,0.027547,0.012337,-0.007904,-0.024654,-0.033564,-0.033361,-0.024913,-0.010439,...,330.834694,398.864910,478.224879,570.398470,677.016725,799.868266,940.910170,1102.279323,1286.304261,1495.517515
27,-4.770775,1.743064,3.949309,3.615470,2.028036,0.078541,-1.659690,-2.863638,-3.401067,-3.278901,...,9952.167068,12157.660264,14758.681815,17810.735335,21375.187655,25519.707886,30318.727316,35853.920579,42214.708602,49498.783770
28,-3.124689,1.176738,2.629529,2.394928,1.323225,0.007860,-1.166094,-1.978794,-2.337570,-2.243679,...,3646.813160,4549.666128,5631.113462,6918.187387,8440.942835,10232.693741,12330.260912,14774.231738,17609.232032,20884.210237
29,0.496991,-0.199388,-0.422434,-0.372377,-0.193020,0.017750,0.198649,0.316801,0.360604,0.333601,...,-1246.794144,-1547.015327,-1902.303242,-2320.371485,-2809.739339,-3379.791241,-4040.839024,-4804.186997,-5682.199932,-6688.374011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
448,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
449,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
450,-0.044559,0.013924,0.035077,0.033779,0.020939,0.004204,-0.011418,-0.022998,-0.029209,-0.029893,...,86.458960,105.697881,128.351102,154.891665,185.842034,221.777757,263.331315,311.196138,366.130804,428.963424
451,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
452,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
453,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
454,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
455,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
456,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
457,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
458,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
459,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
460,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
461,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
462,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
463,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
464,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
465,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
466,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
467,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
468,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
469,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
470,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
471,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
472,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
473,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
474,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
475,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
476,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [156]:
die

array([[  2],
       [  3],
       [  5],
       [  7],
       [  8],
       [  8],
       [ 14],
       [ 14],
       [ 14],
       [ 19],
       [ 19],
       [ 19],
       [ 19],
       [ 25],
       [ 25],
       [ 25],
       [ 25],
       [ 32],
       [ 32],
       [ 32],
       [ 33],
       [ 33],
       [ 33],
       [ 33],
       [ 33],
       [ 34],
       [ 35],
       [ 35],
       [ 35],
       [ 35],
       [ 35],
       [ 35],
       [ 35],
       [ 35],
       [ 37],
       [ 40],
       [ 40],
       [ 41],
       [ 42],
       [ 42],
       [ 43],
       [ 43],
       [ 43],
       [ 47],
       [ 48],
       [ 50],
       [ 50],
       [ 50],
       [ 53],
       [ 59],
       [ 70],
       [ 75],
       [ 82],
       [114],
       [147],
       [177],
       [212],
       [272],
       [322]], dtype=int64)

In [37]:
start = '1/22/2020'
start_date = datetime.datetime.strptime(start, '%m/%d/%Y')
future_forcast_dates = []
for i in range(len(future_forcast)):
    future_forcast_dates.append((start_date + datetime.timedelta(days=i)).strftime('%m/%d/%Y'))

In [38]:
import datetime

In [39]:
start_date

datetime.datetime(2020, 1, 22, 0, 0)

In [40]:
future_forcast_dates

['01/22/2020',
 '01/23/2020',
 '01/24/2020',
 '01/25/2020',
 '01/26/2020',
 '01/27/2020',
 '01/28/2020',
 '01/29/2020',
 '01/30/2020',
 '01/31/2020',
 '02/01/2020',
 '02/02/2020',
 '02/03/2020',
 '02/04/2020',
 '02/05/2020',
 '02/06/2020',
 '02/07/2020',
 '02/08/2020',
 '02/09/2020',
 '02/10/2020',
 '02/11/2020',
 '02/12/2020',
 '02/13/2020',
 '02/14/2020',
 '02/15/2020',
 '02/16/2020',
 '02/17/2020',
 '02/18/2020',
 '02/19/2020',
 '02/20/2020',
 '02/21/2020',
 '02/22/2020',
 '02/23/2020',
 '02/24/2020',
 '02/25/2020',
 '02/26/2020',
 '02/27/2020',
 '02/28/2020',
 '02/29/2020',
 '03/01/2020',
 '03/02/2020',
 '03/03/2020',
 '03/04/2020',
 '03/05/2020',
 '03/06/2020',
 '03/07/2020',
 '03/08/2020',
 '03/09/2020',
 '03/10/2020',
 '03/11/2020',
 '03/12/2020',
 '03/13/2020',
 '03/14/2020',
 '03/15/2020',
 '03/16/2020',
 '03/17/2020',
 '03/18/2020',
 '03/19/2020',
 '03/20/2020',
 '03/21/2020',
 '03/22/2020',
 '03/23/2020',
 '03/24/2020',
 '03/25/2020',
 '03/26/2020',
 '03/27/2020',
 '03/28/2020',
 '03/29/2020',
 '03/30/2020',
 '03/31/2020',
 '04/01/2020',
 '04/02/2020',
 '04/03/2020',
 '04/04/2020']

In [41]:
dates

Index(['1/22/20', '1/23/20', '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       '1/28/20', '1/29/20', '1/30/20', '1/31/20', '2/1/20', '2/2/20',
       '2/3/20', '2/4/20', '2/5/20', '2/6/20', '2/7/20', '2/8/20', '2/9/20',
       '2/10/20', '2/11/20', '2/12/20', '2/13/20', '2/14/20', '2/15/20',
       '2/16/20', '2/17/20', '2/18/20', '2/19/20', '2/20/20', '2/21/20',
       '2/22/20', '2/23/20', '2/24/20', '2/25/20', '2/26/20', '2/27/20',
       '2/28/20', '2/29/20', '3/1/20', '3/2/20', '3/3/20', '3/4/20', '3/5/20',
       '3/6/20', '3/7/20', '3/8/20', '3/9/20', '3/10/20', '3/11/20', '3/12/20',
       '3/13/20', '3/14/20', '3/15/20', '3/16/20', '3/17/20', '3/18/20',
       '3/19/20', '3/20/20'],
      dtype='object')

In [42]:
import random
import math
import time
from sklearn.linear_model import LinearRegression, BayesianRidge
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [43]:
died

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int64)

In [44]:
    die=np.array(confirm.loc[0,dates[0]:dates[-1]]).reshape(-1,1)
    X1_train_confirmed, X1_test_confirmed, y1_train_confirmed, y1_test_confirmed = train_test_split(days_since_1_22,die,test_size=0.20, shuffle=False,random_state=42)
    
    
    from sklearn.svm import LinearSVR
    svm_reg = SVR(kernel="poly",degree=2,C=100,epsilon=0.1) 
    svm_reg.fit(X1_train_confirmed,y1_train_confirmed)

    test_linear_pred = svm_reg.predict(X1_test_confirmed)
    pred1= svm_reg.predict(future_forcast)
    prearr1=np.asarray(pred1).reshape(-1,1)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [ ]:
for i in range(1,477):
    died=np.array(confirm.loc[i,dates[0]:dates[-1]]).reshape(-1,1)
    X1_train_confirmed, X1_test_confirmed, y1_train_confirmed, y1_test_confirmed = train_test_split(days_since_1_22, died, test_size=0.15, shuffle=False)
    svm_reg = SVR(kernel="poly",degree=3,C=100,epsilon=0.1) 
    svm_reg.fit(X1_train_confirmed,y1_train_confirmed)

    test_linear_pred = svm_reg.predict(X1_test_confirmed)
    linear_pred1= svm_reg.predict(future_forcast)
    linarr1=np.asarray(linear_pred1).reshape(-1,1)
    prearr1=np.concatenate((prearr1,linarr1),axis=1)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [ ]:
die

In [ ]:
re.split('[a-c]', '0a3B6', re.I) *prearr1=prearr1.Tre.split('[a-c]', '0a3B6', re.I) *

In [ ]:
dfsvm = pd.DataFrame(prearr1)

In [ ]:
dfsvm

In [1]:
import re

In [2]:
p=re.subn()

TypeError: subn() missing 3 required positional arguments: 'pattern', 'repl', and 'string'

In [3]:
p=re.match()

TypeError: match() missing 2 required positional arguments: 'pattern' and 'string'

In [5]:
re.split('[a-c]', '0a3B6', re.I)

['0', '3B6']

In [7]:
re.sub('morning', 'evening', 'good morning')

'good evening'